//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
    /// <summary>
    /// 实体类OP_BigTemplate。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("OP_BigTemplate")]
    [Serializable]
    public partial class OP_BigTemplate : Entity
    {
        #region Model
		private long _Id;
		private long _HosId;
		private long _CreatorUserId;
		private DateTime _CreationTime;
		private long _LastModifierUserId;
		private DateTime _LastModificationTime;
		private long? _DeleterUserId;
		private DateTime? _DeletionTime;
		private int _DataStatus;
		private int _No;
		private long _DeptId;
		private string _Name;
		private string _Content;
		private int _TemplateType;
		private bool _EffectiveFlag;
		private string _SearchCode;
		private string _WubiCode;

		/// <summary>
		/// ID
		/// </summary>
		[Field("Id")]
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 医疗机构ID
		/// </summary>
		[Field("HosId")]
		public long HosId
		{
			get{ return _HosId; }
			set
			{
				this.OnPropertyValueChange("HosId");
				this._HosId = value;
			}
		}
		/// <summary>
		/// 创建者ID
		/// </summary>
		[Field("CreatorUserId")]
		public long CreatorUserId
		{
			get{ return _CreatorUserId; }
			set
			{
				this.OnPropertyValueChange("CreatorUserId");
				this._CreatorUserId = value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		[Field("CreationTime")]
		public DateTime CreationTime
		{
			get{ return _CreationTime; }
			set
			{
				this.OnPropertyValueChange("CreationTime");
				this._CreationTime = value;
			}
		}
		/// <summary>
		/// 最后修改者ID
		/// </summary>
		[Field("LastModifierUserId")]
		public long LastModifierUserId
		{
			get{ return _LastModifierUserId; }
			set
			{
				this.OnPropertyValueChange("LastModifierUserId");
				this._LastModifierUserId = value;
			}
		}
		/// <summary>
		/// 最后修改时间
		/// </summary>
		[Field("LastModificationTime")]
		public DateTime LastModificationTime
		{
			get{ return _LastModificationTime; }
			set
			{
				this.OnPropertyValueChange("LastModificationTime");
				this._LastModificationTime = value;
			}
		}
		/// <summary>
		/// 删除用户ID
		/// </summary>
		[Field("DeleterUserId")]
		public long? DeleterUserId
		{
			get{ return _DeleterUserId; }
			set
			{
				this.OnPropertyValueChange("DeleterUserId");
				this._DeleterUserId = value;
			}
		}
		/// <summary>
		/// 删除时间
		/// </summary>
		[Field("DeletionTime")]
		public DateTime? DeletionTime
		{
			get{ return _DeletionTime; }
			set
			{
				this.OnPropertyValueChange("DeletionTime");
				this._DeletionTime = value;
			}
		}
		/// <summary>
		/// 数据状态 0停用 1启用 2作废
		/// </summary>
		[Field("DataStatus")]
		public int DataStatus
		{
			get{ return _DataStatus; }
			set
			{
				this.OnPropertyValueChange("DataStatus");
				this._DataStatus = value;
			}
		}
		/// <summary>
		/// 排序号
		/// </summary>
		[Field("No")]
		public int No
		{
			get{ return _No; }
			set
			{
				this.OnPropertyValueChange("No");
				this._No = value;
			}
		}
		/// <summary>
		/// 所属科室ID 0表示全院 非0为科室
		/// </summary>
		[Field("DeptId")]
		public long DeptId
		{
			get{ return _DeptId; }
			set
			{
				this.OnPropertyValueChange("DeptId");
				this._DeptId = value;
			}
		}
		/// <summary>
		/// 模板名称
		/// </summary>
		[Field("Name")]
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange("Name");
				this._Name = value;
			}
		}
		/// <summary>
		/// 模板内容
		/// </summary>
		[Field("Content")]
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange("Content");
				this._Content = value;
			}
		}
		/// <summary>
		/// 初复诊模板标识 0初诊模板 1复诊模板
		/// </summary>
		[Field("TemplateType")]
		public int TemplateType
		{
			get{ return _TemplateType; }
			set
			{
				this.OnPropertyValueChange("TemplateType");
				this._TemplateType = value;
			}
		}
		/// <summary>
		/// 生效标识
		/// </summary>
		[Field("EffectiveFlag")]
		public bool EffectiveFlag
		{
			get{ return _EffectiveFlag; }
			set
			{
				this.OnPropertyValueChange("EffectiveFlag");
				this._EffectiveFlag = value;
			}
		}
		/// <summary>
		/// 拼音码
		/// </summary>
		[Field("SearchCode")]
		public string SearchCode
		{
			get{ return _SearchCode; }
			set
			{
				this.OnPropertyValueChange("SearchCode");
				this._SearchCode = value;
			}
		}
		/// <summary>
		/// 五笔码
		/// </summary>
		[Field("WubiCode")]
		public string WubiCode
		{
			get{ return _WubiCode; }
			set
			{
				this.OnPropertyValueChange("WubiCode");
				this._WubiCode = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.HosId,
				_.CreatorUserId,
				_.CreationTime,
				_.LastModifierUserId,
				_.LastModificationTime,
				_.DeleterUserId,
				_.DeletionTime,
				_.DataStatus,
				_.No,
				_.DeptId,
				_.Name,
				_.Content,
				_.TemplateType,
				_.EffectiveFlag,
				_.SearchCode,
				_.WubiCode,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._HosId,
				this._CreatorUserId,
				this._CreationTime,
				this._LastModifierUserId,
				this._LastModificationTime,
				this._DeleterUserId,
				this._DeletionTime,
				this._DataStatus,
				this._No,
				this._DeptId,
				this._Name,
				this._Content,
				this._TemplateType,
				this._EffectiveFlag,
				this._SearchCode,
				this._WubiCode,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "OP_BigTemplate");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field Id = new Field("Id", "OP_BigTemplate", "ID");
            /// <summary>
			/// 医疗机构ID
			/// </summary>
			public readonly static Field HosId = new Field("HosId", "OP_BigTemplate", "医疗机构ID");
            /// <summary>
			/// 创建者ID
			/// </summary>
			public readonly static Field CreatorUserId = new Field("CreatorUserId", "OP_BigTemplate", "创建者ID");
            /// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreationTime = new Field("CreationTime", "OP_BigTemplate", "创建时间");
            /// <summary>
			/// 最后修改者ID
			/// </summary>
			public readonly static Field LastModifierUserId = new Field("LastModifierUserId", "OP_BigTemplate", "最后修改者ID");
            /// <summary>
			/// 最后修改时间
			/// </summary>
			public readonly static Field LastModificationTime = new Field("LastModificationTime", "OP_BigTemplate", "最后修改时间");
            /// <summary>
			/// 删除用户ID
			/// </summary>
			public readonly static Field DeleterUserId = new Field("DeleterUserId", "OP_BigTemplate", "删除用户ID");
            /// <summary>
			/// 删除时间
			/// </summary>
			public readonly static Field DeletionTime = new Field("DeletionTime", "OP_BigTemplate", "删除时间");
            /// <summary>
			/// 数据状态 0停用 1启用 2作废
			/// </summary>
			public readonly static Field DataStatus = new Field("DataStatus", "OP_BigTemplate", "数据状态 0停用 1启用 2作废");
            /// <summary>
			/// 排序号
			/// </summary>
			public readonly static Field No = new Field("No", "OP_BigTemplate", "排序号");
            /// <summary>
			/// 所属科室ID 0表示全院 非0为科室
			/// </summary>
			public readonly static Field DeptId = new Field("DeptId", "OP_BigTemplate", "所属科室ID 0表示全院 非0为科室");
            /// <summary>
			/// 模板名称
			/// </summary>
			public readonly static Field Name = new Field("Name", "OP_BigTemplate", "模板名称");
            /// <summary>
			/// 模板内容
			/// </summary>
			public readonly static Field Content = new Field("Content", "OP_BigTemplate", "模板内容");
            /// <summary>
			/// 初复诊模板标识 0初诊模板 1复诊模板
			/// </summary>
			public readonly static Field TemplateType = new Field("TemplateType", "OP_BigTemplate", "初复诊模板标识 0初诊模板 1复诊模板");
            /// <summary>
			/// 生效标识
			/// </summary>
			public readonly static Field EffectiveFlag = new Field("EffectiveFlag", "OP_BigTemplate", "生效标识");
            /// <summary>
			/// 拼音码
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode", "OP_BigTemplate", "拼音码");
            /// <summary>
			/// 五笔码
			/// </summary>
			public readonly static Field WubiCode = new Field("WubiCode", "OP_BigTemplate", "五笔码");
        }
        #endregion
	}
}