//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
    /// <summary>
    /// 实体类OP_Journal。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("OP_Journal")]
    [Serializable]
    public partial class OP_Journal : Entity
    {
        #region Model
        private long _Id;
        private long _HosId;
        private long _CreatorUserId;
        private DateTime _CreationTime;
        private long _LastModifierUserId;
        private DateTime _LastModificationTime;
        private long? _DeleterUserId;
        private DateTime? _DeletionTime;
        private int _DataStatus;
        private int _No;
        private long? _FirstAcceptDoctorId;
        private DateTime? _TreatmentTime;
        private string _OutpatientNo;
        private string _PatientName;
        private int _Gender;
        private DateTime? _Birthday;
        private string _Age;
        private long _DeptId;
        private long _DoctorId;
        private string _IDCard;
        private string _CardNo;
        private string _Address;
        private int? _Stature;
        private string _BirthPlace;
        private long _BloodId;
        private int? _Wight;
        private long _MarryId;
        private long _NationalityId;
        private string _Origin;
        private long _NationId;
        private long _KnowlageId;
        private string _Email;
        private string _Phone;
        private string _ContactsPhone;
        private string _ContactsName;
        private long _JobId;
        private string _JobAddress;
        private string _JobPhone;
        private string _Remark;
        private int? _FirstOrSecond;
        private bool _InfectionFlag;
        private int? _BloodPressureHigh;
        private int? _BloodPressureLow;
        private DateTime? _OnsetDate;
        private bool _EffectiveFlag;

        /// <summary>
        /// id
        /// </summary>
        [Field("Id")]
        public long Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 医疗机构ID
        /// </summary>
        [Field("HosId")]
        public long HosId
        {
            get { return _HosId; }
            set
            {
                this.OnPropertyValueChange("HosId");
                this._HosId = value;
            }
        }
        /// <summary>
        /// 创建人编号 当前用户ID
        /// </summary>
        [Field("CreatorUserId")]
        public long CreatorUserId
        {
            get { return _CreatorUserId; }
            set
            {
                this.OnPropertyValueChange("CreatorUserId");
                this._CreatorUserId = value;
            }
        }
        /// <summary>
        /// 创建时间 默认为当前时间
        /// </summary>
        [Field("CreationTime")]
        public DateTime CreationTime
        {
            get { return _CreationTime; }
            set
            {
                this.OnPropertyValueChange("CreationTime");
                this._CreationTime = value;
            }
        }
        /// <summary>
        /// 最后修改人编号
        /// </summary>
        [Field("LastModifierUserId")]
        public long LastModifierUserId
        {
            get { return _LastModifierUserId; }
            set
            {
                this.OnPropertyValueChange("LastModifierUserId");
                this._LastModifierUserId = value;
            }
        }
        /// <summary>
        /// 最后修改时间 默认为当前时间
        /// </summary>
        [Field("LastModificationTime")]
        public DateTime LastModificationTime
        {
            get { return _LastModificationTime; }
            set
            {
                this.OnPropertyValueChange("LastModificationTime");
                this._LastModificationTime = value;
            }
        }
        /// <summary>
        /// 删除人编号
        /// </summary>
        [Field("DeleterUserId")]
        public long? DeleterUserId
        {
            get { return _DeleterUserId; }
            set
            {
                this.OnPropertyValueChange("DeleterUserId");
                this._DeleterUserId = value;
            }
        }
        /// <summary>
        /// 删除时间
        /// </summary>
        [Field("DeletionTime")]
        public DateTime? DeletionTime
        {
            get { return _DeletionTime; }
            set
            {
                this.OnPropertyValueChange("DeletionTime");
                this._DeletionTime = value;
            }
        }
        /// <summary>
        /// 数据状态 0失效 1启用
        /// </summary>
        [Field("DataStatus")]
        public int DataStatus
        {
            get { return _DataStatus; }
            set
            {
                this.OnPropertyValueChange("DataStatus");
                this._DataStatus = value;
            }
        }
        /// <summary>
        /// 排序号
        /// </summary>
        [Field("No")]
        public int No
        {
            get { return _No; }
            set
            {
                this.OnPropertyValueChange("No");
                this._No = value;
            }
        }
        /// <summary>
        /// 首诊医生ID
        /// </summary>
        [Field("FirstAcceptDoctorId")]
        public long? FirstAcceptDoctorId
        {
            get { return _FirstAcceptDoctorId; }
            set
            {
                this.OnPropertyValueChange("FirstAcceptDoctorId");
                this._FirstAcceptDoctorId = value;
            }
        }
        /// <summary>
        /// 就诊时间
        /// </summary>
        [Field("TreatmentTime")]
        public DateTime? TreatmentTime
        {
            get { return _TreatmentTime; }
            set
            {
                this.OnPropertyValueChange("TreatmentTime");
                this._TreatmentTime = value;
            }
        }
        /// <summary>
        /// 就诊号
        /// </summary>
        [Field("OutpatientNo")]
        public string OutpatientNo
        {
            get { return _OutpatientNo; }
            set
            {
                this.OnPropertyValueChange("OutpatientNo");
                this._OutpatientNo = value;
            }
        }
        /// <summary>
        /// 患者姓名
        /// </summary>
        [Field("PatientName")]
        public string PatientName
        {
            get { return _PatientName; }
            set
            {
                this.OnPropertyValueChange("PatientName");
                this._PatientName = value;
            }
        }
        /// <summary>
        /// 患者性别 1男 2女 9其他
        /// </summary>
        [Field("Gender")]
        public int Gender
        {
            get { return _Gender; }
            set
            {
                this.OnPropertyValueChange("Gender");
                this._Gender = value;
            }
        }
        /// <summary>
        /// 出生日期
        /// </summary>
        [Field("Birthday")]
        public DateTime? Birthday
        {
            get { return _Birthday; }
            set
            {
                this.OnPropertyValueChange("Birthday");
                this._Birthday = value;
            }
        }
        /// <summary>
        /// 年龄
        /// </summary>
        [Field("Age")]
        public string Age
        {
            get { return _Age; }
            set
            {
                this.OnPropertyValueChange("Age");
                this._Age = value;
            }
        }
        /// <summary>
        /// 科室Id
        /// </summary>
        [Field("DeptId")]
        public long DeptId
        {
            get { return _DeptId; }
            set
            {
                this.OnPropertyValueChange("DeptId");
                this._DeptId = value;
            }
        }
        /// <summary>
        /// 医生Id
        /// </summary>
        [Field("DoctorId")]
        public long DoctorId
        {
            get { return _DoctorId; }
            set
            {
                this.OnPropertyValueChange("DoctorId");
                this._DoctorId = value;
            }
        }
        /// <summary>
        /// 身份证号
        /// </summary>
        [Field("IDCard")]
        public string IDCard
        {
            get { return _IDCard; }
            set
            {
                this.OnPropertyValueChange("IDCard");
                this._IDCard = value;
            }
        }
        /// <summary>
        /// 医保卡号
        /// </summary>
        [Field("CardNo")]
        public string CardNo
        {
            get { return _CardNo; }
            set
            {
                this.OnPropertyValueChange("CardNo");
                this._CardNo = value;
            }
        }
        /// <summary>
        /// 患者住址
        /// </summary>
        [Field("Address")]
        public string Address
        {
            get { return _Address; }
            set
            {
                this.OnPropertyValueChange("Address");
                this._Address = value;
            }
        }
        /// <summary>
        /// 身高
        /// </summary>
        [Field("Stature")]
        public int? Stature
        {
            get { return _Stature; }
            set
            {
                this.OnPropertyValueChange("Stature");
                this._Stature = value;
            }
        }
        /// <summary>
        /// 出生地
        /// </summary>
        [Field("BirthPlace")]
        public string BirthPlace
        {
            get { return _BirthPlace; }
            set
            {
                this.OnPropertyValueChange("BirthPlace");
                this._BirthPlace = value;
            }
        }
        /// <summary>
        /// 血型Id
        /// </summary>
        [Field("BloodId")]
        public long BloodId
        {
            get { return _BloodId; }
            set
            {
                this.OnPropertyValueChange("BloodId");
                this._BloodId = value;
            }
        }
        /// <summary>
        /// 体重
        /// </summary>
        [Field("Wight")]
        public int? Wight
        {
            get { return _Wight; }
            set
            {
                this.OnPropertyValueChange("Wight");
                this._Wight = value;
            }
        }
        /// <summary>
        /// 婚姻状况
        /// </summary>
        [Field("MarryId")]
        public long MarryId
        {
            get { return _MarryId; }
            set
            {
                this.OnPropertyValueChange("MarryId");
                this._MarryId = value;
            }
        }
        /// <summary>
        /// 国籍
        /// </summary>
        [Field("NationalityId")]
        public long NationalityId
        {
            get { return _NationalityId; }
            set
            {
                this.OnPropertyValueChange("NationalityId");
                this._NationalityId = value;
            }
        }
        /// <summary>
        /// 籍贯
        /// </summary>
        [Field("Origin")]
        public string Origin
        {
            get { return _Origin; }
            set
            {
                this.OnPropertyValueChange("Origin");
                this._Origin = value;
            }
        }
        /// <summary>
        /// 民族
        /// </summary>
        [Field("NationId")]
        public long NationId
        {
            get { return _NationId; }
            set
            {
                this.OnPropertyValueChange("NationId");
                this._NationId = value;
            }
        }
        /// <summary>
        /// 文化程度
        /// </summary>
        [Field("KnowlageId")]
        public long KnowlageId
        {
            get { return _KnowlageId; }
            set
            {
                this.OnPropertyValueChange("KnowlageId");
                this._KnowlageId = value;
            }
        }
        /// <summary>
        /// 邮箱
        /// </summary>
        [Field("Email")]
        public string Email
        {
            get { return _Email; }
            set
            {
                this.OnPropertyValueChange("Email");
                this._Email = value;
            }
        }
        /// <summary>
        /// 手机号
        /// </summary>
        [Field("Phone")]
        public string Phone
        {
            get { return _Phone; }
            set
            {
                this.OnPropertyValueChange("Phone");
                this._Phone = value;
            }
        }
        /// <summary>
        /// 联系人手机号
        /// </summary>
        [Field("ContactsPhone")]
        public string ContactsPhone
        {
            get { return _ContactsPhone; }
            set
            {
                this.OnPropertyValueChange("ContactsPhone");
                this._ContactsPhone = value;
            }
        }
        /// <summary>
        /// 联系人姓名
        /// </summary>
        [Field("ContactsName")]
        public string ContactsName
        {
            get { return _ContactsName; }
            set
            {
                this.OnPropertyValueChange("ContactsName");
                this._ContactsName = value;
            }
        }
        /// <summary>
        /// 职业
        /// </summary>
        [Field("JobId")]
        public long JobId
        {
            get { return _JobId; }
            set
            {
                this.OnPropertyValueChange("JobId");
                this._JobId = value;
            }
        }
        /// <summary>
        /// 工作地址
        /// </summary>
        [Field("JobAddress")]
        public string JobAddress
        {
            get { return _JobAddress; }
            set
            {
                this.OnPropertyValueChange("JobAddress");
                this._JobAddress = value;
            }
        }
        /// <summary>
        /// 单位电话
        /// </summary>
        [Field("JobPhone")]
        public string JobPhone
        {
            get { return _JobPhone; }
            set
            {
                this.OnPropertyValueChange("JobPhone");
                this._JobPhone = value;
            }
        }
        /// <summary>
        /// 备注
        /// </summary>
        [Field("Remark")]
        public string Remark
        {
            get { return _Remark; }
            set
            {
                this.OnPropertyValueChange("Remark");
                this._Remark = value;
            }
        }
        /// <summary>
        /// 复诊还是初诊 0初诊 1复诊
        /// </summary>
        [Field("FirstOrSecond")]
        public int? FirstOrSecond
        {
            get { return _FirstOrSecond; }
            set
            {
                this.OnPropertyValueChange("FirstOrSecond");
                this._FirstOrSecond = value;
            }
        }
        /// <summary>
        /// 是否传染病 0否 1是
        /// </summary>
        [Field("InfectionFlag")]
        public bool InfectionFlag
        {
            get { return _InfectionFlag; }
            set
            {
                this.OnPropertyValueChange("InfectionFlag");
                this._InfectionFlag = value;
            }
        }
        /// <summary>
        /// 血压 高压 收缩压
        /// </summary>
        [Field("BloodPressureHigh")]
        public int? BloodPressureHigh
        {
            get { return _BloodPressureHigh; }
            set
            {
                this.OnPropertyValueChange("BloodPressureHigh");
                this._BloodPressureHigh = value;
            }
        }
        /// <summary>
        /// 血压 低压 舒张压
        /// </summary>
        [Field("BloodPressureLow")]
        public int? BloodPressureLow
        {
            get { return _BloodPressureLow; }
            set
            {
                this.OnPropertyValueChange("BloodPressureLow");
                this._BloodPressureLow = value;
            }
        }
        /// <summary>
        /// 发病日期
        /// </summary>
        [Field("OnsetDate")]
        public DateTime? OnsetDate
        {
            get { return _OnsetDate; }
            set
            {
                this.OnPropertyValueChange("OnsetDate");
                this._OnsetDate = value;
            }
        }
        /// <summary>
        /// 是否为有效的日志 0否 1是
        /// </summary>
        [Field("EffectiveFlag")]
        public bool EffectiveFlag
        {
            get { return _EffectiveFlag; }
            set
            {
                this.OnPropertyValueChange("EffectiveFlag");
                this._EffectiveFlag = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.HosId,
                _.CreatorUserId,
                _.CreationTime,
                _.LastModifierUserId,
                _.LastModificationTime,
                _.DeleterUserId,
                _.DeletionTime,
                _.DataStatus,
                _.No,
                _.FirstAcceptDoctorId,
                _.TreatmentTime,
                _.OutpatientNo,
                _.PatientName,
                _.Gender,
                _.Birthday,
                _.Age,
                _.DeptId,
                _.DoctorId,
                _.IDCard,
                _.CardNo,
                _.Address,
                _.Stature,
                _.BirthPlace,
                _.BloodId,
                _.Wight,
                _.MarryId,
                _.NationalityId,
                _.Origin,
                _.NationId,
                _.KnowlageId,
                _.Email,
                _.Phone,
                _.ContactsPhone,
                _.ContactsName,
                _.JobId,
                _.JobAddress,
                _.JobPhone,
                _.Remark,
                _.FirstOrSecond,
                _.InfectionFlag,
                _.BloodPressureHigh,
                _.BloodPressureLow,
                _.OnsetDate,
                _.EffectiveFlag,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._HosId,
                this._CreatorUserId,
                this._CreationTime,
                this._LastModifierUserId,
                this._LastModificationTime,
                this._DeleterUserId,
                this._DeletionTime,
                this._DataStatus,
                this._No,
                this._FirstAcceptDoctorId,
                this._TreatmentTime,
                this._OutpatientNo,
                this._PatientName,
                this._Gender,
                this._Birthday,
                this._Age,
                this._DeptId,
                this._DoctorId,
                this._IDCard,
                this._CardNo,
                this._Address,
                this._Stature,
                this._BirthPlace,
                this._BloodId,
                this._Wight,
                this._MarryId,
                this._NationalityId,
                this._Origin,
                this._NationId,
                this._KnowlageId,
                this._Email,
                this._Phone,
                this._ContactsPhone,
                this._ContactsName,
                this._JobId,
                this._JobAddress,
                this._JobPhone,
                this._Remark,
                this._FirstOrSecond,
                this._InfectionFlag,
                this._BloodPressureHigh,
                this._BloodPressureLow,
                this._OnsetDate,
                this._EffectiveFlag,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "OP_Journal");
            /// <summary>
			/// id
			/// </summary>
			public readonly static Field Id = new Field("Id", "OP_Journal", "id");
            /// <summary>
			/// 医疗机构ID
			/// </summary>
			public readonly static Field HosId = new Field("HosId", "OP_Journal", "医疗机构ID");
            /// <summary>
			/// 创建人编号 当前用户ID
			/// </summary>
			public readonly static Field CreatorUserId = new Field("CreatorUserId", "OP_Journal", "创建人编号 当前用户ID");
            /// <summary>
			/// 创建时间 默认为当前时间
			/// </summary>
			public readonly static Field CreationTime = new Field("CreationTime", "OP_Journal", "创建时间 默认为当前时间");
            /// <summary>
			/// 最后修改人编号
			/// </summary>
			public readonly static Field LastModifierUserId = new Field("LastModifierUserId", "OP_Journal", "最后修改人编号");
            /// <summary>
			/// 最后修改时间 默认为当前时间
			/// </summary>
			public readonly static Field LastModificationTime = new Field("LastModificationTime", "OP_Journal", "最后修改时间 默认为当前时间");
            /// <summary>
			/// 删除人编号
			/// </summary>
			public readonly static Field DeleterUserId = new Field("DeleterUserId", "OP_Journal", "删除人编号");
            /// <summary>
			/// 删除时间
			/// </summary>
			public readonly static Field DeletionTime = new Field("DeletionTime", "OP_Journal", "删除时间");
            /// <summary>
			/// 数据状态 0失效 1启用
			/// </summary>
			public readonly static Field DataStatus = new Field("DataStatus", "OP_Journal", "数据状态 0失效 1启用");
            /// <summary>
			/// 排序号
			/// </summary>
			public readonly static Field No = new Field("No", "OP_Journal", "排序号");
            /// <summary>
			/// 首诊医生ID
			/// </summary>
			public readonly static Field FirstAcceptDoctorId = new Field("FirstAcceptDoctorId", "OP_Journal", "首诊医生ID");
            /// <summary>
			/// 就诊时间
			/// </summary>
			public readonly static Field TreatmentTime = new Field("TreatmentTime", "OP_Journal", "就诊时间");
            /// <summary>
			/// 就诊号
			/// </summary>
			public readonly static Field OutpatientNo = new Field("OutpatientNo", "OP_Journal", "就诊号");
            /// <summary>
			/// 患者姓名
			/// </summary>
			public readonly static Field PatientName = new Field("PatientName", "OP_Journal", "患者姓名");
            /// <summary>
			/// 患者性别 1男 2女 9其他
			/// </summary>
			public readonly static Field Gender = new Field("Gender", "OP_Journal", "患者性别 1男 2女 9其他");
            /// <summary>
			/// 出生日期
			/// </summary>
			public readonly static Field Birthday = new Field("Birthday", "OP_Journal", "出生日期");
            /// <summary>
			/// 年龄
			/// </summary>
			public readonly static Field Age = new Field("Age", "OP_Journal", "年龄");
            /// <summary>
			/// 科室Id
			/// </summary>
			public readonly static Field DeptId = new Field("DeptId", "OP_Journal", "科室Id");
            /// <summary>
			/// 医生Id
			/// </summary>
			public readonly static Field DoctorId = new Field("DoctorId", "OP_Journal", "医生Id");
            /// <summary>
			/// 身份证号
			/// </summary>
			public readonly static Field IDCard = new Field("IDCard", "OP_Journal", "身份证号");
            /// <summary>
			/// 医保卡号
			/// </summary>
			public readonly static Field CardNo = new Field("CardNo", "OP_Journal", "医保卡号");
            /// <summary>
			/// 患者住址
			/// </summary>
			public readonly static Field Address = new Field("Address", "OP_Journal", "患者住址");
            /// <summary>
			/// 身高
			/// </summary>
			public readonly static Field Stature = new Field("Stature", "OP_Journal", "身高");
            /// <summary>
			/// 出生地
			/// </summary>
			public readonly static Field BirthPlace = new Field("BirthPlace", "OP_Journal", "出生地");
            /// <summary>
			/// 血型Id
			/// </summary>
			public readonly static Field BloodId = new Field("BloodId", "OP_Journal", "血型Id");
            /// <summary>
			/// 体重
			/// </summary>
			public readonly static Field Wight = new Field("Wight", "OP_Journal", "体重");
            /// <summary>
			/// 婚姻状况
			/// </summary>
			public readonly static Field MarryId = new Field("MarryId", "OP_Journal", "婚姻状况");
            /// <summary>
			/// 国籍
			/// </summary>
			public readonly static Field NationalityId = new Field("NationalityId", "OP_Journal", "国籍");
            /// <summary>
			/// 籍贯
			/// </summary>
			public readonly static Field Origin = new Field("Origin", "OP_Journal", "籍贯");
            /// <summary>
			/// 民族
			/// </summary>
			public readonly static Field NationId = new Field("NationId", "OP_Journal", "民族");
            /// <summary>
			/// 文化程度
			/// </summary>
			public readonly static Field KnowlageId = new Field("KnowlageId", "OP_Journal", "文化程度");
            /// <summary>
			/// 邮箱
			/// </summary>
			public readonly static Field Email = new Field("Email", "OP_Journal", "邮箱");
            /// <summary>
			/// 手机号
			/// </summary>
			public readonly static Field Phone = new Field("Phone", "OP_Journal", "手机号");
            /// <summary>
			/// 联系人手机号
			/// </summary>
			public readonly static Field ContactsPhone = new Field("ContactsPhone", "OP_Journal", "联系人手机号");
            /// <summary>
			/// 联系人姓名
			/// </summary>
			public readonly static Field ContactsName = new Field("ContactsName", "OP_Journal", "联系人姓名");
            /// <summary>
			/// 职业
			/// </summary>
			public readonly static Field JobId = new Field("JobId", "OP_Journal", "职业");
            /// <summary>
			/// 工作地址
			/// </summary>
			public readonly static Field JobAddress = new Field("JobAddress", "OP_Journal", "工作地址");
            /// <summary>
			/// 单位电话
			/// </summary>
			public readonly static Field JobPhone = new Field("JobPhone", "OP_Journal", "单位电话");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "OP_Journal", "备注");
            /// <summary>
			/// 复诊还是初诊 0初诊 1复诊
			/// </summary>
			public readonly static Field FirstOrSecond = new Field("FirstOrSecond", "OP_Journal", "复诊还是初诊 0初诊 1复诊");
            /// <summary>
			/// 是否传染病 0否 1是
			/// </summary>
			public readonly static Field InfectionFlag = new Field("InfectionFlag", "OP_Journal", "是否传染病 0否 1是");
            /// <summary>
			/// 血压 高压 收缩压
			/// </summary>
			public readonly static Field BloodPressureHigh = new Field("BloodPressureHigh", "OP_Journal", "血压 高压 收缩压");
            /// <summary>
			/// 血压 低压 舒张压
			/// </summary>
			public readonly static Field BloodPressureLow = new Field("BloodPressureLow", "OP_Journal", "血压 低压 舒张压");
            /// <summary>
			/// 发病日期
			/// </summary>
			public readonly static Field OnsetDate = new Field("OnsetDate", "OP_Journal", "发病日期");
            /// <summary>
			/// 是否为有效的日志 0否 1是
			/// </summary>
			public readonly static Field EffectiveFlag = new Field("EffectiveFlag", "OP_Journal", "是否为有效的日志 0否 1是");
        }
        #endregion
    }
}