//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
    /// <summary>
    /// 实体类OP_PrescriptionGroupDetail。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("OP_PrescriptionGroupDetail")]
    [Serializable]
    public partial class OP_PrescriptionGroupDetail : Entity
    {
        #region Model
		private long _Id;
		private long _HosId;
		private long _CreatorUserId;
		private DateTime _CreationTime;
		private long _LastModifierUserId;
		private DateTime _LastModificationTime;
		private long? _DeleterUserId;
		private DateTime? _DeletionTime;
		private int _DataStatus;
		private int? _No;
		private string _DrugCode;
		private string _ItemCode;
		private int _ItemType;
		private long _GroupId;
		private float? _Dose;
		private string _Usage;
		private string _Interval;
		private int _GroupNo;
		private string _ExecDeptCode;

		/// <summary>
		/// 编号
		/// </summary>
		[Field("Id")]
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("HosId")]
		public long HosId
		{
			get{ return _HosId; }
			set
			{
				this.OnPropertyValueChange("HosId");
				this._HosId = value;
			}
		}
		/// <summary>
		/// 创建人编号 当前用户ID
		/// </summary>
		[Field("CreatorUserId")]
		public long CreatorUserId
		{
			get{ return _CreatorUserId; }
			set
			{
				this.OnPropertyValueChange("CreatorUserId");
				this._CreatorUserId = value;
			}
		}
		/// <summary>
		/// 创建时间 默认为当前时间
		/// </summary>
		[Field("CreationTime")]
		public DateTime CreationTime
		{
			get{ return _CreationTime; }
			set
			{
				this.OnPropertyValueChange("CreationTime");
				this._CreationTime = value;
			}
		}
		/// <summary>
		/// 最后修改人编号
		/// </summary>
		[Field("LastModifierUserId")]
		public long LastModifierUserId
		{
			get{ return _LastModifierUserId; }
			set
			{
				this.OnPropertyValueChange("LastModifierUserId");
				this._LastModifierUserId = value;
			}
		}
		/// <summary>
		/// 最后修改时间 默认为当前时间
		/// </summary>
		[Field("LastModificationTime")]
		public DateTime LastModificationTime
		{
			get{ return _LastModificationTime; }
			set
			{
				this.OnPropertyValueChange("LastModificationTime");
				this._LastModificationTime = value;
			}
		}
		/// <summary>
		/// 删除人编号
		/// </summary>
		[Field("DeleterUserId")]
		public long? DeleterUserId
		{
			get{ return _DeleterUserId; }
			set
			{
				this.OnPropertyValueChange("DeleterUserId");
				this._DeleterUserId = value;
			}
		}
		/// <summary>
		/// 删除时间
		/// </summary>
		[Field("DeletionTime")]
		public DateTime? DeletionTime
		{
			get{ return _DeletionTime; }
			set
			{
				this.OnPropertyValueChange("DeletionTime");
				this._DeletionTime = value;
			}
		}
		/// <summary>
		/// 数据状态 0失效 1启用
		/// </summary>
		[Field("DataStatus")]
		public int DataStatus
		{
			get{ return _DataStatus; }
			set
			{
				this.OnPropertyValueChange("DataStatus");
				this._DataStatus = value;
			}
		}
		/// <summary>
		/// 排序号
		/// </summary>
		[Field("No")]
		public int? No
		{
			get{ return _No; }
			set
			{
				this.OnPropertyValueChange("No");
				this._No = value;
			}
		}
		/// <summary>
		/// 药典Code  非药品不存
		/// </summary>
		[Field("DrugCode")]
		public string DrugCode
		{
			get{ return _DrugCode; }
			set
			{
				this.OnPropertyValueChange("DrugCode");
				this._DrugCode = value;
			}
		}
		/// <summary>
		/// 项目编码
		/// </summary>
		[Field("ItemCode")]
		public string ItemCode
		{
			get{ return _ItemCode; }
			set
			{
				this.OnPropertyValueChange("ItemCode");
				this._ItemCode = value;
			}
		}
		/// <summary>
		/// 项目类型  枚举GroupDetailType    西药=0 中成药=1 草药=2 颗粒剂=3 诊疗=4 检查=5 检验=6 组套=7 普通材料=8 高值耗材=9
		/// </summary>
		[Field("ItemType")]
		public int ItemType
		{
			get{ return _ItemType; }
			set
			{
				this.OnPropertyValueChange("ItemType");
				this._ItemType = value;
			}
		}
		/// <summary>
		/// 套餐ID
		/// </summary>
		[Field("GroupId")]
		public long GroupId
		{
			get{ return _GroupId; }
			set
			{
				this.OnPropertyValueChange("GroupId");
				this._GroupId = value;
			}
		}
		/// <summary>
		/// 一次用量
		/// </summary>
		[Field("Dose")]
		public float? Dose
		{
			get{ return _Dose; }
			set
			{
				this.OnPropertyValueChange("Dose");
				this._Dose = value;
			}
		}
		/// <summary>
		/// 用法
		/// </summary>
		[Field("Usage")]
		public string Usage
		{
			get{ return _Usage; }
			set
			{
				this.OnPropertyValueChange("Usage");
				this._Usage = value;
			}
		}
		/// <summary>
		/// 间隔
		/// </summary>
		[Field("Interval")]
		public string Interval
		{
			get{ return _Interval; }
			set
			{
				this.OnPropertyValueChange("Interval");
				this._Interval = value;
			}
		}
		/// <summary>
		/// 同组编号 不同组为0
		/// </summary>
		[Field("GroupNo")]
		public int GroupNo
		{
			get{ return _GroupNo; }
			set
			{
				this.OnPropertyValueChange("GroupNo");
				this._GroupNo = value;
			}
		}
		/// <summary>
		/// 执行科室ID
		/// </summary>
		[Field("ExecDeptCode")]
		public string ExecDeptCode
		{
			get{ return _ExecDeptCode; }
			set
			{
				this.OnPropertyValueChange("ExecDeptCode");
				this._ExecDeptCode = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.HosId,
				_.CreatorUserId,
				_.CreationTime,
				_.LastModifierUserId,
				_.LastModificationTime,
				_.DeleterUserId,
				_.DeletionTime,
				_.DataStatus,
				_.No,
				_.DrugCode,
				_.ItemCode,
				_.ItemType,
				_.GroupId,
				_.Dose,
				_.Usage,
				_.Interval,
				_.GroupNo,
				_.ExecDeptCode,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._HosId,
				this._CreatorUserId,
				this._CreationTime,
				this._LastModifierUserId,
				this._LastModificationTime,
				this._DeleterUserId,
				this._DeletionTime,
				this._DataStatus,
				this._No,
				this._DrugCode,
				this._ItemCode,
				this._ItemType,
				this._GroupId,
				this._Dose,
				this._Usage,
				this._Interval,
				this._GroupNo,
				this._ExecDeptCode,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "OP_PrescriptionGroupDetail");
            /// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Id = new Field("Id", "OP_PrescriptionGroupDetail", "编号");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HosId = new Field("HosId", "OP_PrescriptionGroupDetail", "");
            /// <summary>
			/// 创建人编号 当前用户ID
			/// </summary>
			public readonly static Field CreatorUserId = new Field("CreatorUserId", "OP_PrescriptionGroupDetail", "创建人编号 当前用户ID");
            /// <summary>
			/// 创建时间 默认为当前时间
			/// </summary>
			public readonly static Field CreationTime = new Field("CreationTime", "OP_PrescriptionGroupDetail", "创建时间 默认为当前时间");
            /// <summary>
			/// 最后修改人编号
			/// </summary>
			public readonly static Field LastModifierUserId = new Field("LastModifierUserId", "OP_PrescriptionGroupDetail", "最后修改人编号");
            /// <summary>
			/// 最后修改时间 默认为当前时间
			/// </summary>
			public readonly static Field LastModificationTime = new Field("LastModificationTime", "OP_PrescriptionGroupDetail", "最后修改时间 默认为当前时间");
            /// <summary>
			/// 删除人编号
			/// </summary>
			public readonly static Field DeleterUserId = new Field("DeleterUserId", "OP_PrescriptionGroupDetail", "删除人编号");
            /// <summary>
			/// 删除时间
			/// </summary>
			public readonly static Field DeletionTime = new Field("DeletionTime", "OP_PrescriptionGroupDetail", "删除时间");
            /// <summary>
			/// 数据状态 0失效 1启用
			/// </summary>
			public readonly static Field DataStatus = new Field("DataStatus", "OP_PrescriptionGroupDetail", "数据状态 0失效 1启用");
            /// <summary>
			/// 排序号
			/// </summary>
			public readonly static Field No = new Field("No", "OP_PrescriptionGroupDetail", "排序号");
            /// <summary>
			/// 药典Code  非药品不存
			/// </summary>
			public readonly static Field DrugCode = new Field("DrugCode", "OP_PrescriptionGroupDetail", "药典Code  非药品不存");
            /// <summary>
			/// 项目编码
			/// </summary>
			public readonly static Field ItemCode = new Field("ItemCode", "OP_PrescriptionGroupDetail", "项目编码");
            /// <summary>
			/// 项目类型  枚举GroupDetailType    西药=0 中成药=1 草药=2 颗粒剂=3 诊疗=4 检查=5 检验=6 组套=7 普通材料=8 高值耗材=9
			/// </summary>
			public readonly static Field ItemType = new Field("ItemType", "OP_PrescriptionGroupDetail", "项目类型  枚举GroupDetailType    西药=0 中成药=1 草药=2 颗粒剂=3 诊疗=4 检查=5 检验=6 组套=7 普通材料=8 高值耗材=9");
            /// <summary>
			/// 套餐ID
			/// </summary>
			public readonly static Field GroupId = new Field("GroupId", "OP_PrescriptionGroupDetail", "套餐ID");
            /// <summary>
			/// 一次用量
			/// </summary>
			public readonly static Field Dose = new Field("Dose", "OP_PrescriptionGroupDetail", "一次用量");
            /// <summary>
			/// 用法
			/// </summary>
			public readonly static Field Usage = new Field("Usage", "OP_PrescriptionGroupDetail", "用法");
            /// <summary>
			/// 间隔
			/// </summary>
			public readonly static Field Interval = new Field("Interval", "OP_PrescriptionGroupDetail", "间隔");
            /// <summary>
			/// 同组编号 不同组为0
			/// </summary>
			public readonly static Field GroupNo = new Field("GroupNo", "OP_PrescriptionGroupDetail", "同组编号 不同组为0");
            /// <summary>
			/// 执行科室ID
			/// </summary>
			public readonly static Field ExecDeptCode = new Field("ExecDeptCode", "OP_PrescriptionGroupDetail", "执行科室ID");
        }
        #endregion
	}
}