//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
    /// <summary>
    /// 实体类OP_Prescription。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("OP_Prescription")]
    [Serializable]
    public partial class OP_Prescription : Entity
    {
        #region Model
		private long _Id;
		private long _HosId;
		private long _CreatorUserId;
		private DateTime _CreationTime;
		private long _LastModifierUserId;
		private DateTime _LastModificationTime;
		private long? _DeleterUserId;
		private DateTime? _DeletionTime;
		private int _DataStatus;
		private int? _No;
		private string _DoctorCode;
		private string _OutpatientNo;
		private string _IDCard;
		private string _CardNo;
		private string _PatientName;
		private int _DetailNumber;
		private string _PrescriptionType;
		private string _DoctorNote;
		private string _ConditionSummary;
		private long? _DeptId;
		private string _DeptCode;
		private int _PrescriptionStatus;
		private bool _EmergencyFlag;
		private int? _HerbalMedicineDose;
		private string _HerbalMedicineUsage;
		private string _DiagnosisCode;
		private int _PrescriptionIndex;

		/// <summary>
		/// 编号
		/// </summary>
		[Field("Id")]
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("HosId")]
		public long HosId
		{
			get{ return _HosId; }
			set
			{
				this.OnPropertyValueChange("HosId");
				this._HosId = value;
			}
		}
		/// <summary>
		/// 创建人编号 当前用户ID
		/// </summary>
		[Field("CreatorUserId")]
		public long CreatorUserId
		{
			get{ return _CreatorUserId; }
			set
			{
				this.OnPropertyValueChange("CreatorUserId");
				this._CreatorUserId = value;
			}
		}
		/// <summary>
		/// 创建时间 默认为当前时间
		/// </summary>
		[Field("CreationTime")]
		public DateTime CreationTime
		{
			get{ return _CreationTime; }
			set
			{
				this.OnPropertyValueChange("CreationTime");
				this._CreationTime = value;
			}
		}
		/// <summary>
		/// 最后修改人编号
		/// </summary>
		[Field("LastModifierUserId")]
		public long LastModifierUserId
		{
			get{ return _LastModifierUserId; }
			set
			{
				this.OnPropertyValueChange("LastModifierUserId");
				this._LastModifierUserId = value;
			}
		}
		/// <summary>
		/// 最后修改时间 默认为当前时间
		/// </summary>
		[Field("LastModificationTime")]
		public DateTime LastModificationTime
		{
			get{ return _LastModificationTime; }
			set
			{
				this.OnPropertyValueChange("LastModificationTime");
				this._LastModificationTime = value;
			}
		}
		/// <summary>
		/// 删除人编号
		/// </summary>
		[Field("DeleterUserId")]
		public long? DeleterUserId
		{
			get{ return _DeleterUserId; }
			set
			{
				this.OnPropertyValueChange("DeleterUserId");
				this._DeleterUserId = value;
			}
		}
		/// <summary>
		/// 删除时间
		/// </summary>
		[Field("DeletionTime")]
		public DateTime? DeletionTime
		{
			get{ return _DeletionTime; }
			set
			{
				this.OnPropertyValueChange("DeletionTime");
				this._DeletionTime = value;
			}
		}
		/// <summary>
		/// 数据状态 0失效 1启用
		/// </summary>
		[Field("DataStatus")]
		public int DataStatus
		{
			get{ return _DataStatus; }
			set
			{
				this.OnPropertyValueChange("DataStatus");
				this._DataStatus = value;
			}
		}
		/// <summary>
		/// 排序号
		/// </summary>
		[Field("No")]
		public int? No
		{
			get{ return _No; }
			set
			{
				this.OnPropertyValueChange("No");
				this._No = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DoctorCode")]
		public string DoctorCode
		{
			get{ return _DoctorCode; }
			set
			{
				this.OnPropertyValueChange("DoctorCode");
				this._DoctorCode = value;
			}
		}
		/// <summary>
		/// 门诊号
		/// </summary>
		[Field("OutpatientNo")]
		public string OutpatientNo
		{
			get{ return _OutpatientNo; }
			set
			{
				this.OnPropertyValueChange("OutpatientNo");
				this._OutpatientNo = value;
			}
		}
		/// <summary>
		/// 身份证号
		/// </summary>
		[Field("IDCard")]
		public string IDCard
		{
			get{ return _IDCard; }
			set
			{
				this.OnPropertyValueChange("IDCard");
				this._IDCard = value;
			}
		}
		/// <summary>
		/// 医保卡号
		/// </summary>
		[Field("CardNo")]
		public string CardNo
		{
			get{ return _CardNo; }
			set
			{
				this.OnPropertyValueChange("CardNo");
				this._CardNo = value;
			}
		}
		/// <summary>
		/// 病人名称
		/// </summary>
		[Field("PatientName")]
		public string PatientName
		{
			get{ return _PatientName; }
			set
			{
				this.OnPropertyValueChange("PatientName");
				this._PatientName = value;
			}
		}
		/// <summary>
		/// 明细数量
		/// </summary>
		[Field("DetailNumber")]
		public int DetailNumber
		{
			get{ return _DetailNumber; }
			set
			{
				this.OnPropertyValueChange("DetailNumber");
				this._DetailNumber = value;
			}
		}
		/// <summary>
		/// 处方类型
		/// </summary>
		[Field("PrescriptionType")]
		public string PrescriptionType
		{
			get{ return _PrescriptionType; }
			set
			{
				this.OnPropertyValueChange("PrescriptionType");
				this._PrescriptionType = value;
			}
		}
		/// <summary>
		/// 医生说明
		/// </summary>
		[Field("DoctorNote")]
		public string DoctorNote
		{
			get{ return _DoctorNote; }
			set
			{
				this.OnPropertyValueChange("DoctorNote");
				this._DoctorNote = value;
			}
		}
		/// <summary>
		/// 病史摘要
		/// </summary>
		[Field("ConditionSummary")]
		public string ConditionSummary
		{
			get{ return _ConditionSummary; }
			set
			{
				this.OnPropertyValueChange("ConditionSummary");
				this._ConditionSummary = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeptId")]
		public long? DeptId
		{
			get{ return _DeptId; }
			set
			{
				this.OnPropertyValueChange("DeptId");
				this._DeptId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeptCode")]
		public string DeptCode
		{
			get{ return _DeptCode; }
			set
			{
				this.OnPropertyValueChange("DeptCode");
				this._DeptCode = value;
			}
		}
		/// <summary>
		/// 处方状态 0新开 1发送 2收费 3作废
		/// </summary>
		[Field("PrescriptionStatus")]
		public int PrescriptionStatus
		{
			get{ return _PrescriptionStatus; }
			set
			{
				this.OnPropertyValueChange("PrescriptionStatus");
				this._PrescriptionStatus = value;
			}
		}
		/// <summary>
		/// 加急标识
		/// </summary>
		[Field("EmergencyFlag")]
		public bool EmergencyFlag
		{
			get{ return _EmergencyFlag; }
			set
			{
				this.OnPropertyValueChange("EmergencyFlag");
				this._EmergencyFlag = value;
			}
		}
		/// <summary>
		/// 草药剂数
		/// </summary>
		[Field("HerbalMedicineDose")]
		public int? HerbalMedicineDose
		{
			get{ return _HerbalMedicineDose; }
			set
			{
				this.OnPropertyValueChange("HerbalMedicineDose");
				this._HerbalMedicineDose = value;
			}
		}
		/// <summary>
		/// 草药用法
		/// </summary>
		[Field("HerbalMedicineUsage")]
		public string HerbalMedicineUsage
		{
			get{ return _HerbalMedicineUsage; }
			set
			{
				this.OnPropertyValueChange("HerbalMedicineUsage");
				this._HerbalMedicineUsage = value;
			}
		}
		/// <summary>
		/// 处方对应诊断编码
		/// </summary>
		[Field("DiagnosisCode")]
		public string DiagnosisCode
		{
			get{ return _DiagnosisCode; }
			set
			{
				this.OnPropertyValueChange("DiagnosisCode");
				this._DiagnosisCode = value;
			}
		}
		/// <summary>
		/// 处方索引
		/// </summary>
		[Field("PrescriptionIndex")]
		public int PrescriptionIndex
		{
			get{ return _PrescriptionIndex; }
			set
			{
				this.OnPropertyValueChange("PrescriptionIndex");
				this._PrescriptionIndex = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.HosId,
				_.CreatorUserId,
				_.CreationTime,
				_.LastModifierUserId,
				_.LastModificationTime,
				_.DeleterUserId,
				_.DeletionTime,
				_.DataStatus,
				_.No,
				_.DoctorCode,
				_.OutpatientNo,
				_.IDCard,
				_.CardNo,
				_.PatientName,
				_.DetailNumber,
				_.PrescriptionType,
				_.DoctorNote,
				_.ConditionSummary,
				_.DeptId,
				_.DeptCode,
				_.PrescriptionStatus,
				_.EmergencyFlag,
				_.HerbalMedicineDose,
				_.HerbalMedicineUsage,
				_.DiagnosisCode,
				_.PrescriptionIndex,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._HosId,
				this._CreatorUserId,
				this._CreationTime,
				this._LastModifierUserId,
				this._LastModificationTime,
				this._DeleterUserId,
				this._DeletionTime,
				this._DataStatus,
				this._No,
				this._DoctorCode,
				this._OutpatientNo,
				this._IDCard,
				this._CardNo,
				this._PatientName,
				this._DetailNumber,
				this._PrescriptionType,
				this._DoctorNote,
				this._ConditionSummary,
				this._DeptId,
				this._DeptCode,
				this._PrescriptionStatus,
				this._EmergencyFlag,
				this._HerbalMedicineDose,
				this._HerbalMedicineUsage,
				this._DiagnosisCode,
				this._PrescriptionIndex,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "OP_Prescription");
            /// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Id = new Field("Id", "OP_Prescription", "编号");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HosId = new Field("HosId", "OP_Prescription", "");
            /// <summary>
			/// 创建人编号 当前用户ID
			/// </summary>
			public readonly static Field CreatorUserId = new Field("CreatorUserId", "OP_Prescription", "创建人编号 当前用户ID");
            /// <summary>
			/// 创建时间 默认为当前时间
			/// </summary>
			public readonly static Field CreationTime = new Field("CreationTime", "OP_Prescription", "创建时间 默认为当前时间");
            /// <summary>
			/// 最后修改人编号
			/// </summary>
			public readonly static Field LastModifierUserId = new Field("LastModifierUserId", "OP_Prescription", "最后修改人编号");
            /// <summary>
			/// 最后修改时间 默认为当前时间
			/// </summary>
			public readonly static Field LastModificationTime = new Field("LastModificationTime", "OP_Prescription", "最后修改时间 默认为当前时间");
            /// <summary>
			/// 删除人编号
			/// </summary>
			public readonly static Field DeleterUserId = new Field("DeleterUserId", "OP_Prescription", "删除人编号");
            /// <summary>
			/// 删除时间
			/// </summary>
			public readonly static Field DeletionTime = new Field("DeletionTime", "OP_Prescription", "删除时间");
            /// <summary>
			/// 数据状态 0失效 1启用
			/// </summary>
			public readonly static Field DataStatus = new Field("DataStatus", "OP_Prescription", "数据状态 0失效 1启用");
            /// <summary>
			/// 排序号
			/// </summary>
			public readonly static Field No = new Field("No", "OP_Prescription", "排序号");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DoctorCode = new Field("DoctorCode", "OP_Prescription", "");
            /// <summary>
			/// 门诊号
			/// </summary>
			public readonly static Field OutpatientNo = new Field("OutpatientNo", "OP_Prescription", "门诊号");
            /// <summary>
			/// 身份证号
			/// </summary>
			public readonly static Field IDCard = new Field("IDCard", "OP_Prescription", "身份证号");
            /// <summary>
			/// 医保卡号
			/// </summary>
			public readonly static Field CardNo = new Field("CardNo", "OP_Prescription", "医保卡号");
            /// <summary>
			/// 病人名称
			/// </summary>
			public readonly static Field PatientName = new Field("PatientName", "OP_Prescription", "病人名称");
            /// <summary>
			/// 明细数量
			/// </summary>
			public readonly static Field DetailNumber = new Field("DetailNumber", "OP_Prescription", "明细数量");
            /// <summary>
			/// 处方类型
			/// </summary>
			public readonly static Field PrescriptionType = new Field("PrescriptionType", "OP_Prescription", "处方类型");
            /// <summary>
			/// 医生说明
			/// </summary>
			public readonly static Field DoctorNote = new Field("DoctorNote", "OP_Prescription", "医生说明");
            /// <summary>
			/// 病史摘要
			/// </summary>
			public readonly static Field ConditionSummary = new Field("ConditionSummary", "OP_Prescription", "病史摘要");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptId = new Field("DeptId", "OP_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptCode = new Field("DeptCode", "OP_Prescription", "");
            /// <summary>
			/// 处方状态 0新开 1发送 2收费 3作废
			/// </summary>
			public readonly static Field PrescriptionStatus = new Field("PrescriptionStatus", "OP_Prescription", "处方状态 0新开 1发送 2收费 3作废");
            /// <summary>
			/// 加急标识
			/// </summary>
			public readonly static Field EmergencyFlag = new Field("EmergencyFlag", "OP_Prescription", "加急标识");
            /// <summary>
			/// 草药剂数
			/// </summary>
			public readonly static Field HerbalMedicineDose = new Field("HerbalMedicineDose", "OP_Prescription", "草药剂数");
            /// <summary>
			/// 草药用法
			/// </summary>
			public readonly static Field HerbalMedicineUsage = new Field("HerbalMedicineUsage", "OP_Prescription", "草药用法");
            /// <summary>
			/// 处方对应诊断编码
			/// </summary>
			public readonly static Field DiagnosisCode = new Field("DiagnosisCode", "OP_Prescription", "处方对应诊断编码");
            /// <summary>
			/// 处方索引
			/// </summary>
			public readonly static Field PrescriptionIndex = new Field("PrescriptionIndex", "OP_Prescription", "处方索引");
        }
        #endregion
	}
}