//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
    /// <summary>
    /// 实体类OP_TemplateSample。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("OP_TemplateSample")]
    [Serializable]
    public partial class OP_TemplateSample : Entity
    {
        #region Model
        private long _Id;
        private long _HosId;
        private long _CreatorUserId;
        private DateTime _CreationTime;
        private long _LastModifierUserId;
        private DateTime _LastModificationTime;
        private long? _DeleterUserId;
        private DateTime? _DeletionTime;
        private int _DataStatus;
        private int _No;
        private long _ParentId;
        private int _NodeType;
        private int _Level;
        private string _Name;
        private long? _OwnerId;
        private string _Content;
        private string _SearchCode;
        private string _WubiCode;

        /// <summary>
        /// 编号
        /// </summary>
        [Field("Id")]
        public long Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("HosId")]
        public long HosId
        {
            get { return _HosId; }
            set
            {
                this.OnPropertyValueChange("HosId");
                this._HosId = value;
            }
        }
        /// <summary>
        /// 创建人编号 当前用户ID
        /// </summary>
        [Field("CreatorUserId")]
        public long CreatorUserId
        {
            get { return _CreatorUserId; }
            set
            {
                this.OnPropertyValueChange("CreatorUserId");
                this._CreatorUserId = value;
            }
        }
        /// <summary>
        /// 创建时间 默认为当前时间
        /// </summary>
        [Field("CreationTime")]
        public DateTime CreationTime
        {
            get { return _CreationTime; }
            set
            {
                this.OnPropertyValueChange("CreationTime");
                this._CreationTime = value;
            }
        }
        /// <summary>
        /// 最后修改人编号
        /// </summary>
        [Field("LastModifierUserId")]
        public long LastModifierUserId
        {
            get { return _LastModifierUserId; }
            set
            {
                this.OnPropertyValueChange("LastModifierUserId");
                this._LastModifierUserId = value;
            }
        }
        /// <summary>
        /// 最后修改时间 默认为当前时间
        /// </summary>
        [Field("LastModificationTime")]
        public DateTime LastModificationTime
        {
            get { return _LastModificationTime; }
            set
            {
                this.OnPropertyValueChange("LastModificationTime");
                this._LastModificationTime = value;
            }
        }
        /// <summary>
        /// 删除人编号
        /// </summary>
        [Field("DeleterUserId")]
        public long? DeleterUserId
        {
            get { return _DeleterUserId; }
            set
            {
                this.OnPropertyValueChange("DeleterUserId");
                this._DeleterUserId = value;
            }
        }
        /// <summary>
        /// 删除时间
        /// </summary>
        [Field("DeletionTime")]
        public DateTime? DeletionTime
        {
            get { return _DeletionTime; }
            set
            {
                this.OnPropertyValueChange("DeletionTime");
                this._DeletionTime = value;
            }
        }
        /// <summary>
        /// 数据状态 0失效 1启用
        /// </summary>
        [Field("DataStatus")]
        public int DataStatus
        {
            get { return _DataStatus; }
            set
            {
                this.OnPropertyValueChange("DataStatus");
                this._DataStatus = value;
            }
        }
        /// <summary>
        /// 排序号
        /// </summary>
        [Field("No")]
        public int No
        {
            get { return _No; }
            set
            {
                this.OnPropertyValueChange("No");
                this._No = value;
            }
        }
        /// <summary>
        /// 父节点Id
        /// </summary>
        [Field("ParentId")]
        public long ParentId
        {
            get { return _ParentId; }
            set
            {
                this.OnPropertyValueChange("ParentId");
                this._ParentId = value;
            }
        }
        /// <summary>
        /// 节点类型 0文件夹 1内容
        /// </summary>
        [Field("NodeType")]
        public int NodeType
        {
            get { return _NodeType; }
            set
            {
                this.OnPropertyValueChange("NodeType");
                this._NodeType = value;
            }
        }
        /// <summary>
        /// 节点等级 0科室 1用户
        /// </summary>
        [Field("Level")]
        public int Level
        {
            get { return _Level; }
            set
            {
                this.OnPropertyValueChange("Level");
                this._Level = value;
            }
        }
        /// <summary>
        /// 模板名称
        /// </summary>
        [Field("Name")]
        public string Name
        {
            get { return _Name; }
            set
            {
                this.OnPropertyValueChange("Name");
                this._Name = value;
            }
        }
        /// <summary>
        /// 拥有者ID
        /// </summary>
        [Field("OwnerId")]
        public long? OwnerId
        {
            get { return _OwnerId; }
            set
            {
                this.OnPropertyValueChange("OwnerId");
                this._OwnerId = value;
            }
        }
        /// <summary>
        /// 模板内容
        /// </summary>
        [Field("Content")]
        public string Content
        {
            get { return _Content; }
            set
            {
                this.OnPropertyValueChange("Content");
                this._Content = value;
            }
        }
        /// <summary>
        /// 拼音码
        /// </summary>
        [Field("SearchCode")]
        public string SearchCode
        {
            get { return _SearchCode; }
            set
            {
                this.OnPropertyValueChange("SearchCode");
                this._SearchCode = value;
            }
        }
        /// <summary>
        /// 五笔码
        /// </summary>
        [Field("WubiCode")]
        public string WubiCode
        {
            get { return _WubiCode; }
            set
            {
                this.OnPropertyValueChange("WubiCode");
                this._WubiCode = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.HosId,
                _.CreatorUserId,
                _.CreationTime,
                _.LastModifierUserId,
                _.LastModificationTime,
                _.DeleterUserId,
                _.DeletionTime,
                _.DataStatus,
                _.No,
                _.ParentId,
                _.NodeType,
                _.Level,
                _.Name,
                _.OwnerId,
                _.Content,
                _.SearchCode,
                _.WubiCode,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._HosId,
                this._CreatorUserId,
                this._CreationTime,
                this._LastModifierUserId,
                this._LastModificationTime,
                this._DeleterUserId,
                this._DeletionTime,
                this._DataStatus,
                this._No,
                this._ParentId,
                this._NodeType,
                this._Level,
                this._Name,
                this._OwnerId,
                this._Content,
                this._SearchCode,
                this._WubiCode,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "OP_TemplateSample");
            /// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Id = new Field("Id", "OP_TemplateSample", "编号");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HosId = new Field("HosId", "OP_TemplateSample", "");
            /// <summary>
			/// 创建人编号 当前用户ID
			/// </summary>
			public readonly static Field CreatorUserId = new Field("CreatorUserId", "OP_TemplateSample", "创建人编号 当前用户ID");
            /// <summary>
			/// 创建时间 默认为当前时间
			/// </summary>
			public readonly static Field CreationTime = new Field("CreationTime", "OP_TemplateSample", "创建时间 默认为当前时间");
            /// <summary>
			/// 最后修改人编号
			/// </summary>
			public readonly static Field LastModifierUserId = new Field("LastModifierUserId", "OP_TemplateSample", "最后修改人编号");
            /// <summary>
			/// 最后修改时间 默认为当前时间
			/// </summary>
			public readonly static Field LastModificationTime = new Field("LastModificationTime", "OP_TemplateSample", "最后修改时间 默认为当前时间");
            /// <summary>
			/// 删除人编号
			/// </summary>
			public readonly static Field DeleterUserId = new Field("DeleterUserId", "OP_TemplateSample", "删除人编号");
            /// <summary>
			/// 删除时间
			/// </summary>
			public readonly static Field DeletionTime = new Field("DeletionTime", "OP_TemplateSample", "删除时间");
            /// <summary>
			/// 数据状态 0失效 1启用
			/// </summary>
			public readonly static Field DataStatus = new Field("DataStatus", "OP_TemplateSample", "数据状态 0失效 1启用");
            /// <summary>
			/// 排序号
			/// </summary>
			public readonly static Field No = new Field("No", "OP_TemplateSample", "排序号");
            /// <summary>
			/// 父节点Id
			/// </summary>
			public readonly static Field ParentId = new Field("ParentId", "OP_TemplateSample", "父节点Id");
            /// <summary>
			/// 节点类型 0文件夹 1内容
			/// </summary>
			public readonly static Field NodeType = new Field("NodeType", "OP_TemplateSample", "节点类型 0文件夹 1内容");
            /// <summary>
			/// 节点等级 0科室 1用户
			/// </summary>
			public readonly static Field Level = new Field("Level", "OP_TemplateSample", "节点等级 0科室 1用户");
            /// <summary>
			/// 模板名称
			/// </summary>
			public readonly static Field Name = new Field("Name", "OP_TemplateSample", "模板名称");
            /// <summary>
			/// 拥有者ID
			/// </summary>
			public readonly static Field OwnerId = new Field("OwnerId", "OP_TemplateSample", "拥有者ID");
            /// <summary>
			/// 模板内容
			/// </summary>
			public readonly static Field Content = new Field("Content", "OP_TemplateSample", "模板内容");
            /// <summary>
            /// 拼音码
            /// </summary>
			public readonly static Field SearchCode = new Field("SearchCode", "OP_TemplateSample", "拼音码");
            /// <summary>
            /// 五笔码
            /// </summary>
			public readonly static Field WubiCode = new Field("WubiCode", "OP_TemplateSample", "五笔码");
        }
        #endregion
    }
}