//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
    /// <summary>
    /// 实体类View_AdviceCategory。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("View_AdviceCategory")]
    [Serializable]
    public partial class View_AdviceCategory : Entity
    {
        #region Model
		private long _Id;
		private long _HosId;
		private int? _DataStatus;
		private int? _No;
		private string _Name;
		private long _ParentId;
		private long? _DeptId;
		private string _DeptName;
		private string _DeptCode;
		private int? _CategoryType;

		/// <summary>
		/// 
		/// </summary>
		[Field("Id")]
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("HosId")]
		public long HosId
		{
			get{ return _HosId; }
			set
			{
				this.OnPropertyValueChange("HosId");
				this._HosId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DataStatus")]
		public int? DataStatus
		{
			get{ return _DataStatus; }
			set
			{
				this.OnPropertyValueChange("DataStatus");
				this._DataStatus = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("No")]
		public int? No
		{
			get{ return _No; }
			set
			{
				this.OnPropertyValueChange("No");
				this._No = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Name")]
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange("Name");
				this._Name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ParentId")]
		public long ParentId
		{
			get{ return _ParentId; }
			set
			{
				this.OnPropertyValueChange("ParentId");
				this._ParentId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeptId")]
		public long? DeptId
		{
			get{ return _DeptId; }
			set
			{
				this.OnPropertyValueChange("DeptId");
				this._DeptId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeptName")]
		public string DeptName
		{
			get{ return _DeptName; }
			set
			{
				this.OnPropertyValueChange("DeptName");
				this._DeptName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeptCode")]
		public string DeptCode
		{
			get{ return _DeptCode; }
			set
			{
				this.OnPropertyValueChange("DeptCode");
				this._DeptCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CategoryType")]
		public int? CategoryType
		{
			get{ return _CategoryType; }
			set
			{
				this.OnPropertyValueChange("CategoryType");
				this._CategoryType = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.HosId,
				_.DataStatus,
				_.No,
				_.Name,
				_.ParentId,
				_.DeptId,
				_.DeptName,
				_.DeptCode,
				_.CategoryType,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._HosId,
				this._DataStatus,
				this._No,
				this._Name,
				this._ParentId,
				this._DeptId,
				this._DeptName,
				this._DeptCode,
				this._CategoryType,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "View_AdviceCategory");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "View_AdviceCategory", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HosId = new Field("HosId", "View_AdviceCategory", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DataStatus = new Field("DataStatus", "View_AdviceCategory", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field No = new Field("No", "View_AdviceCategory", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name", "View_AdviceCategory", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ParentId = new Field("ParentId", "View_AdviceCategory", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptId = new Field("DeptId", "View_AdviceCategory", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptName = new Field("DeptName", "View_AdviceCategory", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptCode = new Field("DeptCode", "View_AdviceCategory", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CategoryType = new Field("CategoryType", "View_AdviceCategory", "");
        }
        #endregion
	}
}