//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
    /// <summary>
    /// 实体类View_Prescription。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("View_Prescription")]
    [Serializable]
    public partial class View_Prescription : Entity
    {
        #region Model
		private long _Id;
		private long _HosId;
		private string _DoctorCode;
		private string _DoctorName;
		private DateTime _CreationTime;
		private string _PrescriptionType;
		private int? _No;
		private string _OutpatientNo;
		private string _PatientName;
		private string _IDCard;
		private string _CardNo;
		private int _DetailNumber;
		private string _DoctorNote;
		private string _ConditionSummary;
		private long? _DeptId;
		private string _DeptName;
		private string _DeptCode;
		private int _PrescriptionStatus;
		private bool _EmergencyFlag;
		private int? _HerbalMedicineDose;
		private string _HerbalMedicineUsage;
		private string _DiagnosisCode;
		private string _DiagnosisName;
		private int _PrescriptionIndex;

		/// <summary>
		/// 
		/// </summary>
		[Field("Id")]
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("HosId")]
		public long HosId
		{
			get{ return _HosId; }
			set
			{
				this.OnPropertyValueChange("HosId");
				this._HosId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DoctorCode")]
		public string DoctorCode
		{
			get{ return _DoctorCode; }
			set
			{
				this.OnPropertyValueChange("DoctorCode");
				this._DoctorCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DoctorName")]
		public string DoctorName
		{
			get{ return _DoctorName; }
			set
			{
				this.OnPropertyValueChange("DoctorName");
				this._DoctorName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreationTime")]
		public DateTime CreationTime
		{
			get{ return _CreationTime; }
			set
			{
				this.OnPropertyValueChange("CreationTime");
				this._CreationTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PrescriptionType")]
		public string PrescriptionType
		{
			get{ return _PrescriptionType; }
			set
			{
				this.OnPropertyValueChange("PrescriptionType");
				this._PrescriptionType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("No")]
		public int? No
		{
			get{ return _No; }
			set
			{
				this.OnPropertyValueChange("No");
				this._No = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("OutpatientNo")]
		public string OutpatientNo
		{
			get{ return _OutpatientNo; }
			set
			{
				this.OnPropertyValueChange("OutpatientNo");
				this._OutpatientNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PatientName")]
		public string PatientName
		{
			get{ return _PatientName; }
			set
			{
				this.OnPropertyValueChange("PatientName");
				this._PatientName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("IDCard")]
		public string IDCard
		{
			get{ return _IDCard; }
			set
			{
				this.OnPropertyValueChange("IDCard");
				this._IDCard = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CardNo")]
		public string CardNo
		{
			get{ return _CardNo; }
			set
			{
				this.OnPropertyValueChange("CardNo");
				this._CardNo = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DetailNumber")]
		public int DetailNumber
		{
			get{ return _DetailNumber; }
			set
			{
				this.OnPropertyValueChange("DetailNumber");
				this._DetailNumber = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DoctorNote")]
		public string DoctorNote
		{
			get{ return _DoctorNote; }
			set
			{
				this.OnPropertyValueChange("DoctorNote");
				this._DoctorNote = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ConditionSummary")]
		public string ConditionSummary
		{
			get{ return _ConditionSummary; }
			set
			{
				this.OnPropertyValueChange("ConditionSummary");
				this._ConditionSummary = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeptId")]
		public long? DeptId
		{
			get{ return _DeptId; }
			set
			{
				this.OnPropertyValueChange("DeptId");
				this._DeptId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeptName")]
		public string DeptName
		{
			get{ return _DeptName; }
			set
			{
				this.OnPropertyValueChange("DeptName");
				this._DeptName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeptCode")]
		public string DeptCode
		{
			get{ return _DeptCode; }
			set
			{
				this.OnPropertyValueChange("DeptCode");
				this._DeptCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PrescriptionStatus")]
		public int PrescriptionStatus
		{
			get{ return _PrescriptionStatus; }
			set
			{
				this.OnPropertyValueChange("PrescriptionStatus");
				this._PrescriptionStatus = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("EmergencyFlag")]
		public bool EmergencyFlag
		{
			get{ return _EmergencyFlag; }
			set
			{
				this.OnPropertyValueChange("EmergencyFlag");
				this._EmergencyFlag = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("HerbalMedicineDose")]
		public int? HerbalMedicineDose
		{
			get{ return _HerbalMedicineDose; }
			set
			{
				this.OnPropertyValueChange("HerbalMedicineDose");
				this._HerbalMedicineDose = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("HerbalMedicineUsage")]
		public string HerbalMedicineUsage
		{
			get{ return _HerbalMedicineUsage; }
			set
			{
				this.OnPropertyValueChange("HerbalMedicineUsage");
				this._HerbalMedicineUsage = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DiagnosisCode")]
		public string DiagnosisCode
		{
			get{ return _DiagnosisCode; }
			set
			{
				this.OnPropertyValueChange("DiagnosisCode");
				this._DiagnosisCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DiagnosisName")]
		public string DiagnosisName
		{
			get{ return _DiagnosisName; }
			set
			{
				this.OnPropertyValueChange("DiagnosisName");
				this._DiagnosisName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PrescriptionIndex")]
		public int PrescriptionIndex
		{
			get{ return _PrescriptionIndex; }
			set
			{
				this.OnPropertyValueChange("PrescriptionIndex");
				this._PrescriptionIndex = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.HosId,
				_.DoctorCode,
				_.DoctorName,
				_.CreationTime,
				_.PrescriptionType,
				_.No,
				_.OutpatientNo,
				_.PatientName,
				_.IDCard,
				_.CardNo,
				_.DetailNumber,
				_.DoctorNote,
				_.ConditionSummary,
				_.DeptId,
				_.DeptName,
				_.DeptCode,
				_.PrescriptionStatus,
				_.EmergencyFlag,
				_.HerbalMedicineDose,
				_.HerbalMedicineUsage,
				_.DiagnosisCode,
				_.DiagnosisName,
				_.PrescriptionIndex,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._HosId,
				this._DoctorCode,
				this._DoctorName,
				this._CreationTime,
				this._PrescriptionType,
				this._No,
				this._OutpatientNo,
				this._PatientName,
				this._IDCard,
				this._CardNo,
				this._DetailNumber,
				this._DoctorNote,
				this._ConditionSummary,
				this._DeptId,
				this._DeptName,
				this._DeptCode,
				this._PrescriptionStatus,
				this._EmergencyFlag,
				this._HerbalMedicineDose,
				this._HerbalMedicineUsage,
				this._DiagnosisCode,
				this._DiagnosisName,
				this._PrescriptionIndex,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "View_Prescription");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HosId = new Field("HosId", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DoctorCode = new Field("DoctorCode", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DoctorName = new Field("DoctorName", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreationTime = new Field("CreationTime", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PrescriptionType = new Field("PrescriptionType", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field No = new Field("No", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field OutpatientNo = new Field("OutpatientNo", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PatientName = new Field("PatientName", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field IDCard = new Field("IDCard", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CardNo = new Field("CardNo", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DetailNumber = new Field("DetailNumber", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DoctorNote = new Field("DoctorNote", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ConditionSummary = new Field("ConditionSummary", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptId = new Field("DeptId", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptName = new Field("DeptName", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptCode = new Field("DeptCode", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PrescriptionStatus = new Field("PrescriptionStatus", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field EmergencyFlag = new Field("EmergencyFlag", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HerbalMedicineDose = new Field("HerbalMedicineDose", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HerbalMedicineUsage = new Field("HerbalMedicineUsage", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DiagnosisCode = new Field("DiagnosisCode", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DiagnosisName = new Field("DiagnosisName", "View_Prescription", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PrescriptionIndex = new Field("PrescriptionIndex", "View_Prescription", "");
        }
        #endregion
	}
}