//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
    /// <summary>
    /// 实体类View_ICD。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("View_ICD")]
    [Serializable]
    public partial class View_ICD : Entity
    {
        #region Model
		private string _Code;
		private string _Name;
		private string _SearchCode;
		private int _Type;
		private int? _Length;

		/// <summary>
		/// 
		/// </summary>
		[Field("Code")]
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange("Code");
				this._Code = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Name")]
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange("Name");
				this._Name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("SearchCode")]
		public string SearchCode
		{
			get{ return _SearchCode; }
			set
			{
				this.OnPropertyValueChange("SearchCode");
				this._SearchCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Type")]
		public int Type
		{
			get{ return _Type; }
			set
			{
				this.OnPropertyValueChange("Type");
				this._Type = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Length")]
		public int? Length
		{
			get{ return _Length; }
			set
			{
				this.OnPropertyValueChange("Length");
				this._Length = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Code,
				_.Name,
				_.SearchCode,
				_.Type,
				_.Length,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Code,
				this._Name,
				this._SearchCode,
				this._Type,
				this._Length,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "View_ICD");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Code = new Field("Code", "View_ICD", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name", "View_ICD", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode", "View_ICD", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Type = new Field("Type", "View_ICD", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Length = new Field("Length", "View_ICD", "");
        }
        #endregion
	}
}