//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
    /// <summary>
    /// 实体类Drug_PriceChangedReceiptDetail。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Drug_PriceChangedReceiptDetail")]
    [Serializable]
    public partial class Drug_PriceChangedReceiptDetail : Entity
    {
        #region Model
        private long _Id;
        private long _HosId;
        private long _ReceiptId;
        private long _CreatorUserId;
        private DateTime _CreationTime;
        private long _LastModifierUserId;
        private DateTime _LastModificationTime;
        private long? _DeleterUserId;
        private DateTime? _DeletionTime;
        private int _DataStatus;
        private int _No;
        private string _ClassCode;
        private string _SpecificationCode;
        private decimal _OldPrice;
        private decimal _NewPrice;
        private decimal _PriceDifference;
        private decimal _RealTimePrice;

        /// <summary>
        /// 编号
        /// </summary>
        [Field("Id")]
        public long Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 医疗机构ID
        /// </summary>
        [Field("HosId")]
        public long HosId
        {
            get { return _HosId; }
            set
            {
                this.OnPropertyValueChange("HosId");
                this._HosId = value;
            }
        }
        /// <summary>
        /// 单据Id
        /// </summary>
        [Field("ReceiptId")]
        public long ReceiptId
        {
            get { return _ReceiptId; }
            set
            {
                this.OnPropertyValueChange("ReceiptId");
                this._ReceiptId = value;
            }
        }
        /// <summary>
        /// 创建人编号 当前用户ID
        /// </summary>
        [Field("CreatorUserId")]
        public long CreatorUserId
        {
            get { return _CreatorUserId; }
            set
            {
                this.OnPropertyValueChange("CreatorUserId");
                this._CreatorUserId = value;
            }
        }
        /// <summary>
        /// 创建时间 默认为当前时间
        /// </summary>
        [Field("CreationTime")]
        public DateTime CreationTime
        {
            get { return _CreationTime; }
            set
            {
                this.OnPropertyValueChange("CreationTime");
                this._CreationTime = value;
            }
        }
        /// <summary>
        /// 最后修改人编号
        /// </summary>
        [Field("LastModifierUserId")]
        public long LastModifierUserId
        {
            get { return _LastModifierUserId; }
            set
            {
                this.OnPropertyValueChange("LastModifierUserId");
                this._LastModifierUserId = value;
            }
        }
        /// <summary>
        /// 最后修改时间 默认为当前时间
        /// </summary>
        [Field("LastModificationTime")]
        public DateTime LastModificationTime
        {
            get { return _LastModificationTime; }
            set
            {
                this.OnPropertyValueChange("LastModificationTime");
                this._LastModificationTime = value;
            }
        }
        /// <summary>
        /// 删除人编号
        /// </summary>
        [Field("DeleterUserId")]
        public long? DeleterUserId
        {
            get { return _DeleterUserId; }
            set
            {
                this.OnPropertyValueChange("DeleterUserId");
                this._DeleterUserId = value;
            }
        }
        /// <summary>
        /// 删除时间
        /// </summary>
        [Field("DeletionTime")]
        public DateTime? DeletionTime
        {
            get { return _DeletionTime; }
            set
            {
                this.OnPropertyValueChange("DeletionTime");
                this._DeletionTime = value;
            }
        }
        /// <summary>
        /// 数据状态 0失效 1启用
        /// </summary>
        [Field("DataStatus")]
        public int DataStatus
        {
            get { return _DataStatus; }
            set
            {
                this.OnPropertyValueChange("DataStatus");
                this._DataStatus = value;
            }
        }
        /// <summary>
        /// 排序号
        /// </summary>
        [Field("No")]
        public int No
        {
            get { return _No; }
            set
            {
                this.OnPropertyValueChange("No");
                this._No = value;
            }
        }
        /// <summary>
        /// 药典编码
        /// </summary>
        [Field("ClassCode")]
        public string ClassCode
        {
            get { return _ClassCode; }
            set
            {
                this.OnPropertyValueChange("ClassCode");
                this._ClassCode = value;
            }
        }
        /// <summary>
        /// 规格编码
        /// </summary>
        [Field("SpecificationCode")]
        public string SpecificationCode
        {
            get { return _SpecificationCode; }
            set
            {
                this.OnPropertyValueChange("SpecificationCode");
                this._SpecificationCode = value;
            }
        }
        /// <summary>
        /// 调价前的单价
        /// </summary>
        [Field("OldPrice")]
        public decimal OldPrice
        {
            get { return _OldPrice; }
            set
            {
                this.OnPropertyValueChange("OldPrice");
                this._OldPrice = value;
            }
        }
        /// <summary>
        /// 调价后的单价
        /// </summary>
        [Field("NewPrice")]
        public decimal NewPrice
        {
            get { return _NewPrice; }
            set
            {
                this.OnPropertyValueChange("NewPrice");
                this._NewPrice = value;
            }
        }
        /// <summary>
        /// 差价
        /// </summary>
        [Field("PriceDifference")]
        public decimal PriceDifference
        {
            get { return _PriceDifference; }
            set
            {
                this.OnPropertyValueChange("PriceDifference");
                this._PriceDifference = value;
            }
        }
        /// <summary>
        /// 实时价格
        /// </summary>
        [Field("RealTimePrice")]
        public decimal RealTimePrice
        {
            get { return _RealTimePrice; }
            set
            {
                this.OnPropertyValueChange("RealTimePrice");
                this._RealTimePrice = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.HosId,
                _.ReceiptId,
                _.CreatorUserId,
                _.CreationTime,
                _.LastModifierUserId,
                _.LastModificationTime,
                _.DeleterUserId,
                _.DeletionTime,
                _.DataStatus,
                _.No,
                _.ClassCode,
                _.SpecificationCode,
                _.OldPrice,
                _.NewPrice,
                _.PriceDifference,
                _.RealTimePrice,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._HosId,
                this._ReceiptId,
                this._CreatorUserId,
                this._CreationTime,
                this._LastModifierUserId,
                this._LastModificationTime,
                this._DeleterUserId,
                this._DeletionTime,
                this._DataStatus,
                this._No,
                this._ClassCode,
                this._SpecificationCode,
                this._OldPrice,
                this._NewPrice,
                this._PriceDifference,
                this._RealTimePrice,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Drug_PriceChangedReceiptDetail");
            /// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Id = new Field("Id", "Drug_PriceChangedReceiptDetail", "编号");
            /// <summary>
			/// 医疗机构ID
			/// </summary>
			public readonly static Field HosId = new Field("HosId", "Drug_PriceChangedReceiptDetail", "医疗机构ID");
            /// <summary>
			/// 单据Id
			/// </summary>
			public readonly static Field ReceiptId = new Field("ReceiptId", "Drug_PriceChangedReceiptDetail", "单据Id");
            /// <summary>
			/// 创建人编号 当前用户ID
			/// </summary>
			public readonly static Field CreatorUserId = new Field("CreatorUserId", "Drug_PriceChangedReceiptDetail", "创建人编号 当前用户ID");
            /// <summary>
			/// 创建时间 默认为当前时间
			/// </summary>
			public readonly static Field CreationTime = new Field("CreationTime", "Drug_PriceChangedReceiptDetail", "创建时间 默认为当前时间");
            /// <summary>
			/// 最后修改人编号
			/// </summary>
			public readonly static Field LastModifierUserId = new Field("LastModifierUserId", "Drug_PriceChangedReceiptDetail", "最后修改人编号");
            /// <summary>
			/// 最后修改时间 默认为当前时间
			/// </summary>
			public readonly static Field LastModificationTime = new Field("LastModificationTime", "Drug_PriceChangedReceiptDetail", "最后修改时间 默认为当前时间");
            /// <summary>
			/// 删除人编号
			/// </summary>
			public readonly static Field DeleterUserId = new Field("DeleterUserId", "Drug_PriceChangedReceiptDetail", "删除人编号");
            /// <summary>
			/// 删除时间
			/// </summary>
			public readonly static Field DeletionTime = new Field("DeletionTime", "Drug_PriceChangedReceiptDetail", "删除时间");
            /// <summary>
			/// 数据状态 0失效 1启用
			/// </summary>
			public readonly static Field DataStatus = new Field("DataStatus", "Drug_PriceChangedReceiptDetail", "数据状态 0失效 1启用");
            /// <summary>
			/// 排序号
			/// </summary>
			public readonly static Field No = new Field("No", "Drug_PriceChangedReceiptDetail", "排序号");
            /// <summary>
			/// 药典编码
			/// </summary>
			public readonly static Field ClassCode = new Field("ClassCode", "Drug_PriceChangedReceiptDetail", "药典编码");
            /// <summary>
			/// 规格编码
			/// </summary>
			public readonly static Field SpecificationCode = new Field("SpecificationCode", "Drug_PriceChangedReceiptDetail", "规格编码");
            /// <summary>
			/// 调价前的单价
			/// </summary>
			public readonly static Field OldPrice = new Field("OldPrice", "Drug_PriceChangedReceiptDetail", "调价前的单价");
            /// <summary>
			/// 调价后的单价
			/// </summary>
			public readonly static Field NewPrice = new Field("NewPrice", "Drug_PriceChangedReceiptDetail", "调价后的单价");
            /// <summary>
			/// 差价
			/// </summary>
			public readonly static Field PriceDifference = new Field("PriceDifference", "Drug_PriceChangedReceiptDetail", "差价");
            /// <summary>
			/// 实时价格
			/// </summary>
			public readonly static Field RealTimePrice = new Field("RealTimePrice", "Drug_PriceChangedReceiptDetail", "实时价格");
        }
        #endregion
    }
}