//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace HIS.Model
{

	/// <summary>
	/// 实体类Drug_PharmacyPriceChangedReceipt 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Drug_PharmacyPriceChangedReceipt")]
	[Serializable]
	public partial class Drug_PharmacyPriceChangedReceipt : Entity 
	{
		#region Model
		private long _Id;
		private long _CreatorUserId;
		private DateTime _CreationTime;
		private long _LastModifierUserId;
		private DateTime _LastModificationTime;
		private long? _DeleterUserId;
		private DateTime? _DeletionTime;
		private int _DataStatus;
		private int _No;
		private long? _AuditUserId;
		private DateTime? _AuditTime;
		private bool _AuditStatus;
		private decimal _TotalPrice;
		private string _Memo;
		private long _DeptId;
		/// <summary>
		/// 编号
		/// </summary>
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 创建人编号 当前用户ID
		/// </summary>
		public long CreatorUserId
		{
			get{ return _CreatorUserId; }
			set
			{
				this.OnPropertyValueChange(_.CreatorUserId,_CreatorUserId,value);
				this._CreatorUserId=value;
			}
		}
		/// <summary>
		/// 创建时间 默认为当前时间
		/// </summary>
		public DateTime CreationTime
		{
			get{ return _CreationTime; }
			set
			{
				this.OnPropertyValueChange(_.CreationTime,_CreationTime,value);
				this._CreationTime=value;
			}
		}
		/// <summary>
		/// 最后修改人编号
		/// </summary>
		public long LastModifierUserId
		{
			get{ return _LastModifierUserId; }
			set
			{
				this.OnPropertyValueChange(_.LastModifierUserId,_LastModifierUserId,value);
				this._LastModifierUserId=value;
			}
		}
		/// <summary>
		/// 最后修改时间 默认为当前时间
		/// </summary>
		public DateTime LastModificationTime
		{
			get{ return _LastModificationTime; }
			set
			{
				this.OnPropertyValueChange(_.LastModificationTime,_LastModificationTime,value);
				this._LastModificationTime=value;
			}
		}
		/// <summary>
		/// 删除人编号
		/// </summary>
		public long? DeleterUserId
		{
			get{ return _DeleterUserId; }
			set
			{
				this.OnPropertyValueChange(_.DeleterUserId,_DeleterUserId,value);
				this._DeleterUserId=value;
			}
		}
		/// <summary>
		/// 删除时间
		/// </summary>
		public DateTime? DeletionTime
		{
			get{ return _DeletionTime; }
			set
			{
				this.OnPropertyValueChange(_.DeletionTime,_DeletionTime,value);
				this._DeletionTime=value;
			}
		}
		/// <summary>
		/// 数据状态 0失效 1启用
		/// </summary>
		public int DataStatus
		{
			get{ return _DataStatus; }
			set
			{
				this.OnPropertyValueChange(_.DataStatus,_DataStatus,value);
				this._DataStatus=value;
			}
		}
		/// <summary>
		/// 排序号
		/// </summary>
		public int No
		{
			get{ return _No; }
			set
			{
				this.OnPropertyValueChange(_.No,_No,value);
				this._No=value;
			}
		}
		/// <summary>
		/// 审核人ID
		/// </summary>
		public long? AuditUserId
		{
			get{ return _AuditUserId; }
			set
			{
				this.OnPropertyValueChange(_.AuditUserId,_AuditUserId,value);
				this._AuditUserId=value;
			}
		}
		/// <summary>
		/// 审核时间
		/// </summary>
		public DateTime? AuditTime
		{
			get{ return _AuditTime; }
			set
			{
				this.OnPropertyValueChange(_.AuditTime,_AuditTime,value);
				this._AuditTime=value;
			}
		}
		/// <summary>
		/// 审核状态 0未审核 1已审核
		/// </summary>
		public bool AuditStatus
		{
			get{ return _AuditStatus; }
			set
			{
				this.OnPropertyValueChange(_.AuditStatus,_AuditStatus,value);
				this._AuditStatus=value;
			}
		}
		/// <summary>
		/// 总价
		/// </summary>
		public decimal TotalPrice
		{
			get{ return _TotalPrice; }
			set
			{
				this.OnPropertyValueChange(_.TotalPrice,_TotalPrice,value);
				this._TotalPrice=value;
			}
		}
		/// <summary>
		/// 备注 调价原因
		/// </summary>
		public string Memo
		{
			get{ return _Memo; }
			set
			{
				this.OnPropertyValueChange(_.Memo,_Memo,value);
				this._Memo=value;
			}
		}
		/// <summary>
		/// 科室ID
		/// </summary>
		public long DeptId
		{
			get{ return _DeptId; }
			set
			{
				this.OnPropertyValueChange(_.DeptId,_DeptId,value);
				this._DeptId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.CreatorUserId,
				_.CreationTime,
				_.LastModifierUserId,
				_.LastModificationTime,
				_.DeleterUserId,
				_.DeletionTime,
				_.DataStatus,
				_.No,
				_.AuditUserId,
				_.AuditTime,
				_.AuditStatus,
				_.TotalPrice,
				_.Memo,
				_.DeptId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._CreatorUserId,
				this._CreationTime,
				this._LastModifierUserId,
				this._LastModificationTime,
				this._DeleterUserId,
				this._DeletionTime,
				this._DataStatus,
				this._No,
				this._AuditUserId,
				this._AuditTime,
				this._AuditStatus,
				this._TotalPrice,
				this._Memo,
				this._DeptId};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Drug_PharmacyPriceChangedReceipt");
			/// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Id = new Field("Id","Drug_PharmacyPriceChangedReceipt","编号");
			/// <summary>
			/// 创建人编号 当前用户ID
			/// </summary>
			public readonly static Field CreatorUserId = new Field("CreatorUserId","Drug_PharmacyPriceChangedReceipt","创建人编号 当前用户ID");
			/// <summary>
			/// 创建时间 默认为当前时间
			/// </summary>
			public readonly static Field CreationTime = new Field("CreationTime","Drug_PharmacyPriceChangedReceipt","创建时间 默认为当前时间");
			/// <summary>
			/// 最后修改人编号
			/// </summary>
			public readonly static Field LastModifierUserId = new Field("LastModifierUserId","Drug_PharmacyPriceChangedReceipt","最后修改人编号");
			/// <summary>
			/// 最后修改时间 默认为当前时间
			/// </summary>
			public readonly static Field LastModificationTime = new Field("LastModificationTime","Drug_PharmacyPriceChangedReceipt","最后修改时间 默认为当前时间");
			/// <summary>
			/// 删除人编号
			/// </summary>
			public readonly static Field DeleterUserId = new Field("DeleterUserId","Drug_PharmacyPriceChangedReceipt","删除人编号");
			/// <summary>
			/// 删除时间
			/// </summary>
			public readonly static Field DeletionTime = new Field("DeletionTime","Drug_PharmacyPriceChangedReceipt","删除时间");
			/// <summary>
			/// 数据状态 0失效 1启用
			/// </summary>
			public readonly static Field DataStatus = new Field("DataStatus","Drug_PharmacyPriceChangedReceipt","数据状态 0失效 1启用");
			/// <summary>
			/// 排序号
			/// </summary>
			public readonly static Field No = new Field("No","Drug_PharmacyPriceChangedReceipt","排序号");
			/// <summary>
			/// 审核人ID
			/// </summary>
			public readonly static Field AuditUserId = new Field("AuditUserId","Drug_PharmacyPriceChangedReceipt","审核人ID");
			/// <summary>
			/// 审核时间
			/// </summary>
			public readonly static Field AuditTime = new Field("AuditTime","Drug_PharmacyPriceChangedReceipt","审核时间");
			/// <summary>
			/// 审核状态 0未审核 1已审核
			/// </summary>
			public readonly static Field AuditStatus = new Field("AuditStatus","Drug_PharmacyPriceChangedReceipt","审核状态 0未审核 1已审核");
			/// <summary>
			/// 总价
			/// </summary>
			public readonly static Field TotalPrice = new Field("TotalPrice","Drug_PharmacyPriceChangedReceipt","总价");
			/// <summary>
			/// 备注 调价原因
			/// </summary>
			public readonly static Field Memo = new Field("Memo","Drug_PharmacyPriceChangedReceipt","备注 调价原因");
			/// <summary>
			/// 科室ID
			/// </summary>
			public readonly static Field DeptId = new Field("DeptId","Drug_PharmacyPriceChangedReceipt","科室ID");
		}
		#endregion


	}
}

