//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
    /// <summary>
    /// 实体类Drug_WholehospitalSpecification。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Drug_WholehospitalSpecification")]
    [Serializable]
    public partial class Drug_WholehospitalSpecification : Entity
    {
        #region Model
		private long _Id;
		private long _HosId;
		private long _CreatorUserId;
		private DateTime _CreationTime;
		private long _LastModifierUserId;
		private DateTime _LastModificationTime;
		private long? _DeleterUserId;
		private DateTime? _DeletionTime;
		private int _DataStatus;
		private int _No;
		private string _ClassCode;
		private string _Code;
		private string _Specification;
		private string _TradeName;
		private int _PackageNumber;
		private string _BigPackageUnit;
		private string _SmallPackageUnit;
		private float? _MinDose;
		private string _MinDoseUnit;
		private float? _DDD;
		private string _DDDSpecification;
		private string _BarCode;
		private int _ChargeType;
		private string _Manufacturer;
		private string _ApprovalNumber;
		private string _SearchCode;
		private string _WubiCode;
		private int _UpperLimit;
		private int _LowerLimit;

        /// <summary>
        /// 编号
        /// </summary>
        [Field("Id")]
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("HosId")]
		public long HosId
		{
			get{ return _HosId; }
			set
			{
				this.OnPropertyValueChange("HosId");
				this._HosId = value;
			}
		}
		/// <summary>
		/// 创建人编号 当前用户ID
		/// </summary>
		[Field("CreatorUserId")]
		public long CreatorUserId
		{
			get{ return _CreatorUserId; }
			set
			{
				this.OnPropertyValueChange("CreatorUserId");
				this._CreatorUserId = value;
			}
		}
		/// <summary>
		/// 创建时间 默认为当前时间
		/// </summary>
		[Field("CreationTime")]
		public DateTime CreationTime
		{
			get{ return _CreationTime; }
			set
			{
				this.OnPropertyValueChange("CreationTime");
				this._CreationTime = value;
			}
		}
		/// <summary>
		/// 最后修改人编号
		/// </summary>
		[Field("LastModifierUserId")]
		public long LastModifierUserId
		{
			get{ return _LastModifierUserId; }
			set
			{
				this.OnPropertyValueChange("LastModifierUserId");
				this._LastModifierUserId = value;
			}
		}
		/// <summary>
		/// 最后修改时间 默认为当前时间
		/// </summary>
		[Field("LastModificationTime")]
		public DateTime LastModificationTime
		{
			get{ return _LastModificationTime; }
			set
			{
				this.OnPropertyValueChange("LastModificationTime");
				this._LastModificationTime = value;
			}
		}
		/// <summary>
		/// 删除人编号
		/// </summary>
		[Field("DeleterUserId")]
		public long? DeleterUserId
		{
			get{ return _DeleterUserId; }
			set
			{
				this.OnPropertyValueChange("DeleterUserId");
				this._DeleterUserId = value;
			}
		}
		/// <summary>
		/// 删除时间
		/// </summary>
		[Field("DeletionTime")]
		public DateTime? DeletionTime
		{
			get{ return _DeletionTime; }
			set
			{
				this.OnPropertyValueChange("DeletionTime");
				this._DeletionTime = value;
			}
		}
		/// <summary>
		/// 数据状态 0失效 1启用
		/// </summary>
		[Field("DataStatus")]
		public int DataStatus
		{
			get{ return _DataStatus; }
			set
			{
				this.OnPropertyValueChange("DataStatus");
				this._DataStatus = value;
			}
		}
		/// <summary>
		/// 排序号
		/// </summary>
		[Field("No")]
		public int No
		{
			get{ return _No; }
			set
			{
				this.OnPropertyValueChange("No");
				this._No = value;
			}
		}
		/// <summary>
		/// 药典编码
		/// </summary>
		[Field("ClassCode")]
		public string ClassCode
		{
			get{ return _ClassCode; }
			set
			{
				this.OnPropertyValueChange("ClassCode");
				this._ClassCode = value;
			}
		}
		/// <summary>
		/// 规格编码
		/// </summary>
		[Field("Code")]
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange("Code");
				this._Code = value;
			}
		}
		/// <summary>
		/// 规格
		/// </summary>
		[Field("Specification")]
		public string Specification
		{
			get{ return _Specification; }
			set
			{
				this.OnPropertyValueChange("Specification");
				this._Specification = value;
			}
		}
		/// <summary>
		/// 商品名
		/// </summary>
		[Field("TradeName")]
		public string TradeName
		{
			get{ return _TradeName; }
			set
			{
				this.OnPropertyValueChange("TradeName");
				this._TradeName = value;
			}
		}
		/// <summary>
		/// 包装数
		/// </summary>
		[Field("PackageNumber")]
		public int PackageNumber
		{
			get{ return _PackageNumber; }
			set
			{
				this.OnPropertyValueChange("PackageNumber");
				this._PackageNumber = value;
			}
		}
		/// <summary>
		/// 大包装单位
		/// </summary>
		[Field("BigPackageUnit")]
		public string BigPackageUnit
		{
			get{ return _BigPackageUnit; }
			set
			{
				this.OnPropertyValueChange("BigPackageUnit");
				this._BigPackageUnit = value;
			}
		}
		/// <summary>
		/// 小包装单位
		/// </summary>
		[Field("SmallPackageUnit")]
		public string SmallPackageUnit
		{
			get{ return _SmallPackageUnit; }
			set
			{
				this.OnPropertyValueChange("SmallPackageUnit");
				this._SmallPackageUnit = value;
			}
		}
		/// <summary>
		/// 最小剂量
		/// </summary>
		[Field("MinDose")]
		public float? MinDose
		{
			get{ return _MinDose; }
			set
			{
				this.OnPropertyValueChange("MinDose");
				this._MinDose = value;
			}
		}
		/// <summary>
		/// 最小剂量单位
		/// </summary>
		[Field("MinDoseUnit")]
		public string MinDoseUnit
		{
			get{ return _MinDoseUnit; }
			set
			{
				this.OnPropertyValueChange("MinDoseUnit");
				this._MinDoseUnit = value;
			}
		}
		/// <summary>
		/// DDD值
		/// </summary>
		[Field("DDD")]
		public float? DDD
		{
			get{ return _DDD; }
			set
			{
				this.OnPropertyValueChange("DDD");
				this._DDD = value;
			}
		}
		/// <summary>
		/// DDD规格
		/// </summary>
		[Field("DDDSpecification")]
		public string DDDSpecification
		{
			get{ return _DDDSpecification; }
			set
			{
				this.OnPropertyValueChange("DDDSpecification");
				this._DDDSpecification = value;
			}
		}
		/// <summary>
		/// 条形码
		/// </summary>
		[Field("BarCode")]
		public string BarCode
		{
			get{ return _BarCode; }
			set
			{
				this.OnPropertyValueChange("BarCode");
				this._BarCode = value;
			}
		}
		/// <summary>
		/// 计费方式 0 按次取整  1按量取整
		/// </summary>
		[Field("ChargeType")]
		public int ChargeType
		{
			get{ return _ChargeType; }
			set
			{
				this.OnPropertyValueChange("ChargeType");
				this._ChargeType = value;
			}
		}
		/// <summary>
		/// 生产厂家
		/// </summary>
		[Field("Manufacturer")]
		public string Manufacturer
		{
			get{ return _Manufacturer; }
			set
			{
				this.OnPropertyValueChange("Manufacturer");
				this._Manufacturer = value;
			}
		}
		/// <summary>
		/// 批准文号
		/// </summary>
		[Field("ApprovalNumber")]
		public string ApprovalNumber
		{
			get{ return _ApprovalNumber; }
			set
			{
				this.OnPropertyValueChange("ApprovalNumber");
				this._ApprovalNumber = value;
			}
		}
		/// <summary>
		/// 拼音码
		/// </summary>
		[Field("SearchCode")]
		public string SearchCode
		{
			get{ return _SearchCode; }
			set
			{
				this.OnPropertyValueChange("SearchCode");
				this._SearchCode = value;
			}
		}
		/// <summary>
		/// 五笔码
		/// </summary>
		[Field("WubiCode")]
		public string WubiCode
		{
			get{ return _WubiCode; }
			set
			{
				this.OnPropertyValueChange("WubiCode");
				this._WubiCode = value;
			}
		}
        /// <summary>
        /// 上限
        /// </summary>
        [Field("UpperLimit")]
        public int UpperLimit
        {
            get { return _UpperLimit; }
            set
            {
                this.OnPropertyValueChange("UpperLimit");
                this._UpperLimit = value;
            }
        }
        /// <summary>
        /// 下限
        /// </summary>
        [Field("LowerLimit")]
        public int LowerLimit
        {
            get { return _LowerLimit; }
            set
            {
                this.OnPropertyValueChange("LowerLimit");
                this._LowerLimit = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.HosId,
				_.CreatorUserId,
				_.CreationTime,
				_.LastModifierUserId,
				_.LastModificationTime,
				_.DeleterUserId,
				_.DeletionTime,
				_.DataStatus,
				_.No,
				_.ClassCode,
				_.Code,
				_.Specification,
				_.TradeName,
				_.PackageNumber,
				_.BigPackageUnit,
				_.SmallPackageUnit,
				_.MinDose,
				_.MinDoseUnit,
				_.DDD,
				_.DDDSpecification,
				_.BarCode,
				_.ChargeType,
				_.Manufacturer,
				_.ApprovalNumber,
				_.SearchCode,
				_.WubiCode,
				_.UpperLimit,
				_.LowerLimit,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._HosId,
				this._CreatorUserId,
				this._CreationTime,
				this._LastModifierUserId,
				this._LastModificationTime,
				this._DeleterUserId,
				this._DeletionTime,
				this._DataStatus,
				this._No,
				this._ClassCode,
				this._Code,
				this._Specification,
				this._TradeName,
				this._PackageNumber,
				this._BigPackageUnit,
				this._SmallPackageUnit,
				this._MinDose,
				this._MinDoseUnit,
				this._DDD,
				this._DDDSpecification,
				this._BarCode,
				this._ChargeType,
				this._Manufacturer,
				this._ApprovalNumber,
				this._SearchCode,
				this._WubiCode,
				this._UpperLimit,
				this._LowerLimit,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Drug_WholehospitalSpecification");
            /// <summary>
			/// 编号
			/// </summary>
			public readonly static Field Id = new Field("Id", "Drug_WholehospitalSpecification", "编号");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HosId = new Field("HosId", "Drug_WholehospitalSpecification", "");
            /// <summary>
			/// 创建人编号 当前用户ID
			/// </summary>
			public readonly static Field CreatorUserId = new Field("CreatorUserId", "Drug_WholehospitalSpecification", "创建人编号 当前用户ID");
            /// <summary>
			/// 创建时间 默认为当前时间
			/// </summary>
			public readonly static Field CreationTime = new Field("CreationTime", "Drug_WholehospitalSpecification", "创建时间 默认为当前时间");
            /// <summary>
			/// 最后修改人编号
			/// </summary>
			public readonly static Field LastModifierUserId = new Field("LastModifierUserId", "Drug_WholehospitalSpecification", "最后修改人编号");
            /// <summary>
			/// 最后修改时间 默认为当前时间
			/// </summary>
			public readonly static Field LastModificationTime = new Field("LastModificationTime", "Drug_WholehospitalSpecification", "最后修改时间 默认为当前时间");
            /// <summary>
			/// 删除人编号
			/// </summary>
			public readonly static Field DeleterUserId = new Field("DeleterUserId", "Drug_WholehospitalSpecification", "删除人编号");
            /// <summary>
			/// 删除时间
			/// </summary>
			public readonly static Field DeletionTime = new Field("DeletionTime", "Drug_WholehospitalSpecification", "删除时间");
            /// <summary>
			/// 数据状态 0失效 1启用
			/// </summary>
			public readonly static Field DataStatus = new Field("DataStatus", "Drug_WholehospitalSpecification", "数据状态 0失效 1启用");
            /// <summary>
			/// 排序号
			/// </summary>
			public readonly static Field No = new Field("No", "Drug_WholehospitalSpecification", "排序号");
            /// <summary>
			/// 药典编码
			/// </summary>
			public readonly static Field ClassCode = new Field("ClassCode", "Drug_WholehospitalSpecification", "药典编码");
            /// <summary>
			/// 规格编码
			/// </summary>
			public readonly static Field Code = new Field("Code", "Drug_WholehospitalSpecification", "规格编码");
            /// <summary>
			/// 规格
			/// </summary>
			public readonly static Field Specification = new Field("Specification", "Drug_WholehospitalSpecification", "规格");
            /// <summary>
			/// 商品名
			/// </summary>
			public readonly static Field TradeName = new Field("TradeName", "Drug_WholehospitalSpecification", "商品名");
            /// <summary>
			/// 包装数
			/// </summary>
			public readonly static Field PackageNumber = new Field("PackageNumber", "Drug_WholehospitalSpecification", "包装数");
            /// <summary>
			/// 大包装单位
			/// </summary>
			public readonly static Field BigPackageUnit = new Field("BigPackageUnit", "Drug_WholehospitalSpecification", "大包装单位");
            /// <summary>
			/// 小包装单位
			/// </summary>
			public readonly static Field SmallPackageUnit = new Field("SmallPackageUnit", "Drug_WholehospitalSpecification", "小包装单位");
            /// <summary>
			/// 最小剂量
			/// </summary>
			public readonly static Field MinDose = new Field("MinDose", "Drug_WholehospitalSpecification", "最小剂量");
            /// <summary>
			/// 最小剂量单位
			/// </summary>
			public readonly static Field MinDoseUnit = new Field("MinDoseUnit", "Drug_WholehospitalSpecification", "最小剂量单位");
            /// <summary>
			/// DDD值
			/// </summary>
			public readonly static Field DDD = new Field("DDD", "Drug_WholehospitalSpecification", "DDD值");
            /// <summary>
			/// DDD规格
			/// </summary>
			public readonly static Field DDDSpecification = new Field("DDDSpecification", "Drug_WholehospitalSpecification", "DDD规格");
            /// <summary>
			/// 条形码
			/// </summary>
			public readonly static Field BarCode = new Field("BarCode", "Drug_WholehospitalSpecification", "条形码");
            /// <summary>
			/// 计费方式 0 按次取整  1按量取整
			/// </summary>
			public readonly static Field ChargeType = new Field("ChargeType", "Drug_WholehospitalSpecification", "计费方式 0 按次取整  1按量取整");
            /// <summary>
			/// 生产厂家
			/// </summary>
			public readonly static Field Manufacturer = new Field("Manufacturer", "Drug_WholehospitalSpecification", "生产厂家");
            /// <summary>
			/// 批准文号
			/// </summary>
			public readonly static Field ApprovalNumber = new Field("ApprovalNumber", "Drug_WholehospitalSpecification", "批准文号");
            /// <summary>
			/// 拼音码
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode", "Drug_WholehospitalSpecification", "拼音码");
            /// <summary>
			/// 五笔码
			/// </summary>
			public readonly static Field WubiCode = new Field("WubiCode", "Drug_WholehospitalSpecification", "五笔码");
            /// <summary>
            /// 上限
            /// </summary>
			public readonly static Field UpperLimit = new Field("UpperLimit", "Drug_WholehospitalSpecification", "上限");
            /// <summary>
            /// 下限
            /// </summary>
			public readonly static Field LowerLimit = new Field("LowerLimit", "Drug_WholehospitalSpecification", "下限");
        }
        #endregion
	}
}