//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
	/// <summary>
	/// 实体类Dic_DrugformUsageMapper。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Dic_DrugformUsageMapper")]
	[Serializable]
	public partial class Dic_DrugformUsageMapper : Entity
	{
		#region Model
		private long _HosId;
		private long _DrugformId;
		private long _UsageId;
		private bool _IsDefault;

		/// <summary>
		/// 医疗机构ID
		/// </summary>
		[Field("HosId")]
		public long HosId
		{
			get { return _HosId; }
			set
			{
				this.OnPropertyValueChange("HosId");
				this._HosId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DrugformId")]
		public long DrugformId
		{
			get { return _DrugformId; }
			set
			{
				this.OnPropertyValueChange("DrugformId");
				this._DrugformId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("UsageId")]
		public long UsageId
		{
			get { return _UsageId; }
			set
			{
				this.OnPropertyValueChange("UsageId");
				this._UsageId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("IsDefault")]
		public bool IsDefault
		{
			get { return _IsDefault; }
			set
			{
				this.OnPropertyValueChange("IsDefault");
				this._IsDefault = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.HosId,
				_.DrugformId,
				_.UsageId,
				_.IsDefault,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._HosId,
				this._DrugformId,
				this._UsageId,
				this._IsDefault,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Dic_DrugformUsageMapper");
			/// <summary>
			/// 医疗机构ID
			/// </summary>
			public readonly static Field HosId = new Field("HosId", "Dic_DrugformUsageMapper", "医疗机构ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DrugformId = new Field("DrugformId", "Dic_DrugformUsageMapper", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UsageId = new Field("UsageId", "Dic_DrugformUsageMapper", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsDefault = new Field("IsDefault", "Dic_DrugformUsageMapper", "");
		}
		#endregion
	}
}