//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
    /// <summary>
    /// 实体类Dic_Merchants。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Dic_Merchants")]
    [Serializable]
    public partial class Dic_Merchants : Entity
    {
        #region Model
        private long _Id;
        private long _CreatorUserId;
        private DateTime _CreationTime;
        private long _LastModifierUserId;
        private DateTime _LastModificationTime;
        private long? _DeleterUserId;
        private DateTime? _DeletionTime;
        private int _DataStatus;
        private int _No;
        private string _Name;
        private string _LegalPerson;
        private string _Address;
        private string _PhoneNo;
        private string _BusinessLicense;
        private int _Type;
        private string _SearchCode;
        private string _WubiCode;

        /// <summary>
        /// ID
        /// </summary>
        [Field("Id")]
        public long Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 创建人ID
        /// </summary>
        [Field("CreatorUserId")]
        public long CreatorUserId
        {
            get { return _CreatorUserId; }
            set
            {
                this.OnPropertyValueChange("CreatorUserId");
                this._CreatorUserId = value;
            }
        }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Field("CreationTime")]
        public DateTime CreationTime
        {
            get { return _CreationTime; }
            set
            {
                this.OnPropertyValueChange("CreationTime");
                this._CreationTime = value;
            }
        }
        /// <summary>
        /// 最后修改人ID
        /// </summary>
        [Field("LastModifierUserId")]
        public long LastModifierUserId
        {
            get { return _LastModifierUserId; }
            set
            {
                this.OnPropertyValueChange("LastModifierUserId");
                this._LastModifierUserId = value;
            }
        }
        /// <summary>
        /// 最后修改时间
        /// </summary>
        [Field("LastModificationTime")]
        public DateTime LastModificationTime
        {
            get { return _LastModificationTime; }
            set
            {
                this.OnPropertyValueChange("LastModificationTime");
                this._LastModificationTime = value;
            }
        }
        /// <summary>
        /// 删除者ID
        /// </summary>
        [Field("DeleterUserId")]
        public long? DeleterUserId
        {
            get { return _DeleterUserId; }
            set
            {
                this.OnPropertyValueChange("DeleterUserId");
                this._DeleterUserId = value;
            }
        }
        /// <summary>
        /// 删除时间
        /// </summary>
        [Field("DeletionTime")]
        public DateTime? DeletionTime
        {
            get { return _DeletionTime; }
            set
            {
                this.OnPropertyValueChange("DeletionTime");
                this._DeletionTime = value;
            }
        }
        /// <summary>
        /// 数据状态 0停用 1启用 2作废
        /// </summary>
        [Field("DataStatus")]
        public int DataStatus
        {
            get { return _DataStatus; }
            set
            {
                this.OnPropertyValueChange("DataStatus");
                this._DataStatus = value;
            }
        }
        /// <summary>
        /// 顺序号
        /// </summary>
        [Field("No")]
        public int No
        {
            get { return _No; }
            set
            {
                this.OnPropertyValueChange("No");
                this._No = value;
            }
        }
        /// <summary>
        /// 厂商名称
        /// </summary>
        [Field("Name")]
        public string Name
        {
            get { return _Name; }
            set
            {
                this.OnPropertyValueChange("Name");
                this._Name = value;
            }
        }
        /// <summary>
        /// 法人
        /// </summary>
        [Field("LegalPerson")]
        public string LegalPerson
        {
            get { return _LegalPerson; }
            set
            {
                this.OnPropertyValueChange("LegalPerson");
                this._LegalPerson = value;
            }
        }
        /// <summary>
        /// 生产经营地址
        /// </summary>
        [Field("Address")]
        public string Address
        {
            get { return _Address; }
            set
            {
                this.OnPropertyValueChange("Address");
                this._Address = value;
            }
        }
        /// <summary>
        /// 联系电话
        /// </summary>
        [Field("PhoneNo")]
        public string PhoneNo
        {
            get { return _PhoneNo; }
            set
            {
                this.OnPropertyValueChange("PhoneNo");
                this._PhoneNo = value;
            }
        }
        /// <summary>
        /// 营业执照
        /// </summary>
        [Field("BusinessLicense")]
        public string BusinessLicense
        {
            get { return _BusinessLicense; }
            set
            {
                this.OnPropertyValueChange("BusinessLicense");
                this._BusinessLicense = value;
            }
        }
        /// <summary>
        /// 厂商类型  1、生产厂家 2、供应厂商
        /// </summary>
        [Field("Type")]
        public int Type
        {
            get { return _Type; }
            set
            {
                this.OnPropertyValueChange("Type");
                this._Type = value;
            }
        }
        /// <summary>
        /// 拼音码
        /// </summary>
        [Field("SearchCode")]
        public string SearchCode
        {
            get { return _SearchCode; }
            set
            {
                this.OnPropertyValueChange("SearchCode");
                this._SearchCode = value;
            }
        }
        /// <summary>
        /// 五笔码
        /// </summary>
        [Field("WubiCode")]
        public string WubiCode
        {
            get { return _WubiCode; }
            set
            {
                this.OnPropertyValueChange("WubiCode");
                this._WubiCode = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.CreatorUserId,
                _.CreationTime,
                _.LastModifierUserId,
                _.LastModificationTime,
                _.DeleterUserId,
                _.DeletionTime,
                _.DataStatus,
                _.No,
                _.Name,
                _.LegalPerson,
                _.Address,
                _.PhoneNo,
                _.BusinessLicense,
                _.Type,
                _.SearchCode,
                _.WubiCode,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._CreatorUserId,
                this._CreationTime,
                this._LastModifierUserId,
                this._LastModificationTime,
                this._DeleterUserId,
                this._DeletionTime,
                this._DataStatus,
                this._No,
                this._Name,
                this._LegalPerson,
                this._Address,
                this._PhoneNo,
                this._BusinessLicense,
                this._Type,
                this._SearchCode,
                this._WubiCode,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Dic_Merchants");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field Id = new Field("Id", "Dic_Merchants", "ID");
            /// <summary>
			/// 创建人ID
			/// </summary>
			public readonly static Field CreatorUserId = new Field("CreatorUserId", "Dic_Merchants", "创建人ID");
            /// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreationTime = new Field("CreationTime", "Dic_Merchants", "创建时间");
            /// <summary>
			/// 最后修改人ID
			/// </summary>
			public readonly static Field LastModifierUserId = new Field("LastModifierUserId", "Dic_Merchants", "最后修改人ID");
            /// <summary>
			/// 最后修改时间
			/// </summary>
			public readonly static Field LastModificationTime = new Field("LastModificationTime", "Dic_Merchants", "最后修改时间");
            /// <summary>
			/// 删除者ID
			/// </summary>
			public readonly static Field DeleterUserId = new Field("DeleterUserId", "Dic_Merchants", "删除者ID");
            /// <summary>
			/// 删除时间
			/// </summary>
			public readonly static Field DeletionTime = new Field("DeletionTime", "Dic_Merchants", "删除时间");
            /// <summary>
			/// 数据状态 0停用 1启用 2作废
			/// </summary>
			public readonly static Field DataStatus = new Field("DataStatus", "Dic_Merchants", "数据状态 0停用 1启用 2作废");
            /// <summary>
			/// 顺序号
			/// </summary>
			public readonly static Field No = new Field("No", "Dic_Merchants", "顺序号");
            /// <summary>
			/// 厂商名称
			/// </summary>
			public readonly static Field Name = new Field("Name", "Dic_Merchants", "厂商名称");
            /// <summary>
			/// 法人
			/// </summary>
			public readonly static Field LegalPerson = new Field("LegalPerson", "Dic_Merchants", "法人");
            /// <summary>
			/// 生产经营地址
			/// </summary>
			public readonly static Field Address = new Field("Address", "Dic_Merchants", "生产经营地址");
            /// <summary>
			/// 联系电话
			/// </summary>
			public readonly static Field PhoneNo = new Field("PhoneNo", "Dic_Merchants", "联系电话");
            /// <summary>
			/// 营业执照
			/// </summary>
			public readonly static Field BusinessLicense = new Field("BusinessLicense", "Dic_Merchants", "营业执照");
            /// <summary>
			/// 厂商类型  1、生产厂家 2、供应厂商
			/// </summary>
			public readonly static Field Type = new Field("Type", "Dic_Merchants", "厂商类型  1、生产厂家 2、供应厂商");
            /// <summary>
			/// 拼音码
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode", "Dic_Merchants", "拼音码");
            /// <summary>
			/// 五笔码
			/// </summary>
			public readonly static Field WubiCode = new Field("WubiCode", "Dic_Merchants", "五笔码");
        }
        #endregion
    }
}