//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
    /// <summary>
    /// 实体类Dic_Catalog。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Dic_Catalog")]
    [Serializable]
    public partial class Dic_Catalog : Entity
    {
        #region Model
		private long _Id;
		private long _HosId;
		private long _ParentId;
		private string _Name;
		private int _NodeType;
		private string _Description;
		private string _CreatorUserId;
		private DateTime _CreationTime;
		private string _DeleterUserId;
		private DateTime? _DeletionTime;
		private string _LastModifierUserId;
		private DateTime _LastModificationTime;
		private int _DataStatus;
		private int _No;

		/// <summary>
		/// 
		/// </summary>
		[Field("Id")]
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("HosId")]
		public long HosId
		{
			get{ return _HosId; }
			set
			{
				this.OnPropertyValueChange("HosId");
				this._HosId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ParentId")]
		public long ParentId
		{
			get{ return _ParentId; }
			set
			{
				this.OnPropertyValueChange("ParentId");
				this._ParentId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Name")]
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange("Name");
				this._Name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("NodeType")]
		public int NodeType
		{
			get{ return _NodeType; }
			set
			{
				this.OnPropertyValueChange("NodeType");
				this._NodeType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Description")]
		public string Description
		{
			get{ return _Description; }
			set
			{
				this.OnPropertyValueChange("Description");
				this._Description = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreatorUserId")]
		public string CreatorUserId
		{
			get{ return _CreatorUserId; }
			set
			{
				this.OnPropertyValueChange("CreatorUserId");
				this._CreatorUserId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreationTime")]
		public DateTime CreationTime
		{
			get{ return _CreationTime; }
			set
			{
				this.OnPropertyValueChange("CreationTime");
				this._CreationTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeleterUserId")]
		public string DeleterUserId
		{
			get{ return _DeleterUserId; }
			set
			{
				this.OnPropertyValueChange("DeleterUserId");
				this._DeleterUserId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DeletionTime")]
		public DateTime? DeletionTime
		{
			get{ return _DeletionTime; }
			set
			{
				this.OnPropertyValueChange("DeletionTime");
				this._DeletionTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LastModifierUserId")]
		public string LastModifierUserId
		{
			get{ return _LastModifierUserId; }
			set
			{
				this.OnPropertyValueChange("LastModifierUserId");
				this._LastModifierUserId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("LastModificationTime")]
		public DateTime LastModificationTime
		{
			get{ return _LastModificationTime; }
			set
			{
				this.OnPropertyValueChange("LastModificationTime");
				this._LastModificationTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("DataStatus")]
		public int DataStatus
		{
			get{ return _DataStatus; }
			set
			{
				this.OnPropertyValueChange("DataStatus");
				this._DataStatus = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("No")]
		public int No
		{
			get{ return _No; }
			set
			{
				this.OnPropertyValueChange("No");
				this._No = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.HosId,
				_.ParentId,
				_.Name,
				_.NodeType,
				_.Description,
				_.CreatorUserId,
				_.CreationTime,
				_.DeleterUserId,
				_.DeletionTime,
				_.LastModifierUserId,
				_.LastModificationTime,
				_.DataStatus,
				_.No,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._HosId,
				this._ParentId,
				this._Name,
				this._NodeType,
				this._Description,
				this._CreatorUserId,
				this._CreationTime,
				this._DeleterUserId,
				this._DeletionTime,
				this._LastModifierUserId,
				this._LastModificationTime,
				this._DataStatus,
				this._No,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Dic_Catalog");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "Dic_Catalog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HosId = new Field("HosId", "Dic_Catalog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ParentId = new Field("ParentId", "Dic_Catalog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name", "Dic_Catalog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field NodeType = new Field("NodeType", "Dic_Catalog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Description = new Field("Description", "Dic_Catalog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreatorUserId = new Field("CreatorUserId", "Dic_Catalog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreationTime = new Field("CreationTime", "Dic_Catalog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeleterUserId = new Field("DeleterUserId", "Dic_Catalog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeletionTime = new Field("DeletionTime", "Dic_Catalog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field LastModifierUserId = new Field("LastModifierUserId", "Dic_Catalog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field LastModificationTime = new Field("LastModificationTime", "Dic_Catalog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DataStatus = new Field("DataStatus", "Dic_Catalog", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field No = new Field("No", "Dic_Catalog", "");
        }
        #endregion
	}
}