//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
    /// <summary>
    /// 实体类Dic_FeeItem。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Dic_FeeItem")]
    [Serializable]
    public partial class Dic_FeeItem : Entity
    {
        #region Model
		private long _Id;
		private long _HosId;
		private string _Code;
		private string _Name;
		private int _No;
		private long _CreatorUserId;
		private DateTime _CreationTime;
		private long _LastModifierUserId;
		private DateTime _LastModificationTime;
		private long? _DeleterUserId;
		private DateTime? _DeletionTime;
		private int _DataStatus;
		private string _Specification;
		private decimal? _Measure;
		private string _MeasureUnit;
		private decimal? _Price;
		private long? _ExecDeptId;
		private string _FinanceTypeCode;
		private string _SearchCode;
		private string _WubiCode;
		private bool _OFlag;
		private bool _IFlag;
		private bool _SFlag;
		private bool _MFlag;
		private bool _VariableFlag;

		/// <summary>
		/// ID
		/// </summary>
		[Field("Id")]
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 医疗机构ID
		/// </summary>
		[Field("HosId")]
		public long HosId
		{
			get{ return _HosId; }
			set
			{
				this.OnPropertyValueChange("HosId");
				this._HosId = value;
			}
		}
		/// <summary>
		/// 代码
		/// </summary>
		[Field("Code")]
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange("Code");
				this._Code = value;
			}
		}
		/// <summary>
		/// 名称
		/// </summary>
		[Field("Name")]
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange("Name");
				this._Name = value;
			}
		}
		/// <summary>
		/// 序号
		/// </summary>
		[Field("No")]
		public int No
		{
			get{ return _No; }
			set
			{
				this.OnPropertyValueChange("No");
				this._No = value;
			}
		}
		/// <summary>
		/// 创建者ID
		/// </summary>
		[Field("CreatorUserId")]
		public long CreatorUserId
		{
			get{ return _CreatorUserId; }
			set
			{
				this.OnPropertyValueChange("CreatorUserId");
				this._CreatorUserId = value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		[Field("CreationTime")]
		public DateTime CreationTime
		{
			get{ return _CreationTime; }
			set
			{
				this.OnPropertyValueChange("CreationTime");
				this._CreationTime = value;
			}
		}
		/// <summary>
		/// 最后的修改者ID
		/// </summary>
		[Field("LastModifierUserId")]
		public long LastModifierUserId
		{
			get{ return _LastModifierUserId; }
			set
			{
				this.OnPropertyValueChange("LastModifierUserId");
				this._LastModifierUserId = value;
			}
		}
		/// <summary>
		/// 最后的修改时间
		/// </summary>
		[Field("LastModificationTime")]
		public DateTime LastModificationTime
		{
			get{ return _LastModificationTime; }
			set
			{
				this.OnPropertyValueChange("LastModificationTime");
				this._LastModificationTime = value;
			}
		}
		/// <summary>
		/// 删除者ID
		/// </summary>
		[Field("DeleterUserId")]
		public long? DeleterUserId
		{
			get{ return _DeleterUserId; }
			set
			{
				this.OnPropertyValueChange("DeleterUserId");
				this._DeleterUserId = value;
			}
		}
		/// <summary>
		/// 删除时间
		/// </summary>
		[Field("DeletionTime")]
		public DateTime? DeletionTime
		{
			get{ return _DeletionTime; }
			set
			{
				this.OnPropertyValueChange("DeletionTime");
				this._DeletionTime = value;
			}
		}
		/// <summary>
		/// 状态 状态 0停用 1启用 2作废
		/// </summary>
		[Field("DataStatus")]
		public int DataStatus
		{
			get{ return _DataStatus; }
			set
			{
				this.OnPropertyValueChange("DataStatus");
				this._DataStatus = value;
			}
		}
		/// <summary>
		/// 规格
		/// </summary>
		[Field("Specification")]
		public string Specification
		{
			get{ return _Specification; }
			set
			{
				this.OnPropertyValueChange("Specification");
				this._Specification = value;
			}
		}
		/// <summary>
		/// 最小计量
		/// </summary>
		[Field("Measure")]
		public decimal? Measure
		{
			get{ return _Measure; }
			set
			{
				this.OnPropertyValueChange("Measure");
				this._Measure = value;
			}
		}
		/// <summary>
		/// 计量单位
		/// </summary>
		[Field("MeasureUnit")]
		public string MeasureUnit
		{
			get{ return _MeasureUnit; }
			set
			{
				this.OnPropertyValueChange("MeasureUnit");
				this._MeasureUnit = value;
			}
		}
		/// <summary>
		/// 价格
		/// </summary>
		[Field("Price")]
		public decimal? Price
		{
			get{ return _Price; }
			set
			{
				this.OnPropertyValueChange("Price");
				this._Price = value;
			}
		}
		/// <summary>
		/// 默认执行科室
		/// </summary>
		[Field("ExecDeptId")]
		public long? ExecDeptId
		{
			get{ return _ExecDeptId; }
			set
			{
				this.OnPropertyValueChange("ExecDeptId");
				this._ExecDeptId = value;
			}
		}
		/// <summary>
		/// 财务分类 sys_Dic 中code 为  “FinanceType”
		/// </summary>
		[Field("FinanceTypeCode")]
		public string FinanceTypeCode
		{
			get{ return _FinanceTypeCode; }
			set
			{
				this.OnPropertyValueChange("FinanceTypeCode");
				this._FinanceTypeCode = value;
			}
		}
		/// <summary>
		/// 拼音码
		/// </summary>
		[Field("SearchCode")]
		public string SearchCode
		{
			get{ return _SearchCode; }
			set
			{
				this.OnPropertyValueChange("SearchCode");
				this._SearchCode = value;
			}
		}
		/// <summary>
		/// 五笔码
		/// </summary>
		[Field("WubiCode")]
		public string WubiCode
		{
			get{ return _WubiCode; }
			set
			{
				this.OnPropertyValueChange("WubiCode");
				this._WubiCode = value;
			}
		}
		/// <summary>
		/// 门诊可用标志
		/// </summary>
		[Field("OFlag")]
		public bool OFlag
		{
			get{ return _OFlag; }
			set
			{
				this.OnPropertyValueChange("OFlag");
				this._OFlag = value;
			}
		}
		/// <summary>
		/// 住院可用标志
		/// </summary>
		[Field("IFlag")]
		public bool IFlag
		{
			get{ return _IFlag; }
			set
			{
				this.OnPropertyValueChange("IFlag");
				this._IFlag = value;
			}
		}
		/// <summary>
		/// 手术室可用标志
		/// </summary>
		[Field("SFlag")]
		public bool SFlag
		{
			get{ return _SFlag; }
			set
			{
				this.OnPropertyValueChange("SFlag");
				this._SFlag = value;
			}
		}
		/// <summary>
		/// 医技可用标志
		/// </summary>
		[Field("MFlag")]
		public bool MFlag
		{
			get{ return _MFlag; }
			set
			{
				this.OnPropertyValueChange("MFlag");
				this._MFlag = value;
			}
		}
		/// <summary>
		/// 价格是否可变
		/// </summary>
		[Field("VariableFlag")]
		public bool VariableFlag
		{
			get{ return _VariableFlag; }
			set
			{
				this.OnPropertyValueChange("VariableFlag");
				this._VariableFlag = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.HosId,
				_.Code,
				_.Name,
				_.No,
				_.CreatorUserId,
				_.CreationTime,
				_.LastModifierUserId,
				_.LastModificationTime,
				_.DeleterUserId,
				_.DeletionTime,
				_.DataStatus,
				_.Specification,
				_.Measure,
				_.MeasureUnit,
				_.Price,
				_.ExecDeptId,
				_.FinanceTypeCode,
				_.SearchCode,
				_.WubiCode,
				_.OFlag,
				_.IFlag,
				_.SFlag,
				_.MFlag,
				_.VariableFlag,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._HosId,
				this._Code,
				this._Name,
				this._No,
				this._CreatorUserId,
				this._CreationTime,
				this._LastModifierUserId,
				this._LastModificationTime,
				this._DeleterUserId,
				this._DeletionTime,
				this._DataStatus,
				this._Specification,
				this._Measure,
				this._MeasureUnit,
				this._Price,
				this._ExecDeptId,
				this._FinanceTypeCode,
				this._SearchCode,
				this._WubiCode,
				this._OFlag,
				this._IFlag,
				this._SFlag,
				this._MFlag,
				this._VariableFlag,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Dic_FeeItem");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field Id = new Field("Id", "Dic_FeeItem", "ID");
            /// <summary>
			/// 医疗机构ID
			/// </summary>
			public readonly static Field HosId = new Field("HosId", "Dic_FeeItem", "医疗机构ID");
            /// <summary>
			/// 代码
			/// </summary>
			public readonly static Field Code = new Field("Code", "Dic_FeeItem", "代码");
            /// <summary>
			/// 名称
			/// </summary>
			public readonly static Field Name = new Field("Name", "Dic_FeeItem", "名称");
            /// <summary>
			/// 序号
			/// </summary>
			public readonly static Field No = new Field("No", "Dic_FeeItem", "序号");
            /// <summary>
			/// 创建者ID
			/// </summary>
			public readonly static Field CreatorUserId = new Field("CreatorUserId", "Dic_FeeItem", "创建者ID");
            /// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreationTime = new Field("CreationTime", "Dic_FeeItem", "创建时间");
            /// <summary>
			/// 最后的修改者ID
			/// </summary>
			public readonly static Field LastModifierUserId = new Field("LastModifierUserId", "Dic_FeeItem", "最后的修改者ID");
            /// <summary>
			/// 最后的修改时间
			/// </summary>
			public readonly static Field LastModificationTime = new Field("LastModificationTime", "Dic_FeeItem", "最后的修改时间");
            /// <summary>
			/// 删除者ID
			/// </summary>
			public readonly static Field DeleterUserId = new Field("DeleterUserId", "Dic_FeeItem", "删除者ID");
            /// <summary>
			/// 删除时间
			/// </summary>
			public readonly static Field DeletionTime = new Field("DeletionTime", "Dic_FeeItem", "删除时间");
            /// <summary>
			/// 状态 状态 0停用 1启用 2作废
			/// </summary>
			public readonly static Field DataStatus = new Field("DataStatus", "Dic_FeeItem", "状态 状态 0停用 1启用 2作废");
            /// <summary>
			/// 规格
			/// </summary>
			public readonly static Field Specification = new Field("Specification", "Dic_FeeItem", "规格");
            /// <summary>
			/// 最小计量
			/// </summary>
			public readonly static Field Measure = new Field("Measure", "Dic_FeeItem", "最小计量");
            /// <summary>
			/// 计量单位
			/// </summary>
			public readonly static Field MeasureUnit = new Field("MeasureUnit", "Dic_FeeItem", "计量单位");
            /// <summary>
			/// 价格
			/// </summary>
			public readonly static Field Price = new Field("Price", "Dic_FeeItem", "价格");
            /// <summary>
			/// 默认执行科室
			/// </summary>
			public readonly static Field ExecDeptId = new Field("ExecDeptId", "Dic_FeeItem", "默认执行科室");
            /// <summary>
			/// 财务分类 sys_Dic 中code 为  “FinanceType”
			/// </summary>
			public readonly static Field FinanceTypeCode = new Field("FinanceTypeCode", "Dic_FeeItem", "财务分类 sys_Dic 中code 为  “FinanceType”");
            /// <summary>
			/// 拼音码
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode", "Dic_FeeItem", "拼音码");
            /// <summary>
			/// 五笔码
			/// </summary>
			public readonly static Field WubiCode = new Field("WubiCode", "Dic_FeeItem", "五笔码");
            /// <summary>
			/// 门诊可用标志
			/// </summary>
			public readonly static Field OFlag = new Field("OFlag", "Dic_FeeItem", "门诊可用标志");
            /// <summary>
			/// 住院可用标志
			/// </summary>
			public readonly static Field IFlag = new Field("IFlag", "Dic_FeeItem", "住院可用标志");
            /// <summary>
			/// 手术室可用标志
			/// </summary>
			public readonly static Field SFlag = new Field("SFlag", "Dic_FeeItem", "手术室可用标志");
            /// <summary>
			/// 医技可用标志
			/// </summary>
			public readonly static Field MFlag = new Field("MFlag", "Dic_FeeItem", "医技可用标志");
            /// <summary>
			/// 价格是否可变
			/// </summary>
			public readonly static Field VariableFlag = new Field("VariableFlag", "Dic_FeeItem", "价格是否可变");
        }
        #endregion
	}
}