//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
    /// <summary>
    /// 实体类Dic_Title。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Dic_Title")]
    [Serializable]
    public partial class Dic_Title : Entity
    {
        #region Model
		private long _Id;
		private long _HosId;
		private string _Code;
		private string _Name;
		private int _TitleLevel;
		private int _Scope;
		private string _SearchCode;
		private long _CreatorUserId;
		private DateTime _CreationTime;
		private long? _DeleterUserId;
		private DateTime? _DeletionTime;
		private long _LastModifierUserId;
		private DateTime _LastModificationTime;
		private int _DataStatus;
		private int _No;

		/// <summary>
		/// ID
		/// </summary>
		[Field("Id")]
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 医疗机构ID
		/// </summary>
		[Field("HosId")]
		public long HosId
		{
			get{ return _HosId; }
			set
			{
				this.OnPropertyValueChange("HosId");
				this._HosId = value;
			}
		}
		/// <summary>
		/// 职称编码
		/// </summary>
		[Field("Code")]
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange("Code");
				this._Code = value;
			}
		}
		/// <summary>
		/// 职称名称
		/// </summary>
		[Field("Name")]
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange("Name");
				this._Name = value;
			}
		}
		/// <summary>
		/// 职称等级
		/// </summary>
		[Field("TitleLevel")]
		public int TitleLevel
		{
			get{ return _TitleLevel; }
			set
			{
				this.OnPropertyValueChange("TitleLevel");
				this._TitleLevel = value;
			}
		}
		/// <summary>
		/// 范畴 1 医生 2 护士 9其他
		/// </summary>
		[Field("Scope")]
		public int Scope
		{
			get{ return _Scope; }
			set
			{
				this.OnPropertyValueChange("Scope");
				this._Scope = value;
			}
		}
		/// <summary>
		/// 检索码
		/// </summary>
		[Field("SearchCode")]
		public string SearchCode
		{
			get{ return _SearchCode; }
			set
			{
				this.OnPropertyValueChange("SearchCode");
				this._SearchCode = value;
			}
		}
		/// <summary>
		/// 创建者ID
		/// </summary>
		[Field("CreatorUserId")]
		public long CreatorUserId
		{
			get{ return _CreatorUserId; }
			set
			{
				this.OnPropertyValueChange("CreatorUserId");
				this._CreatorUserId = value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		[Field("CreationTime")]
		public DateTime CreationTime
		{
			get{ return _CreationTime; }
			set
			{
				this.OnPropertyValueChange("CreationTime");
				this._CreationTime = value;
			}
		}
		/// <summary>
		/// 删除者ID
		/// </summary>
		[Field("DeleterUserId")]
		public long? DeleterUserId
		{
			get{ return _DeleterUserId; }
			set
			{
				this.OnPropertyValueChange("DeleterUserId");
				this._DeleterUserId = value;
			}
		}
		/// <summary>
		/// 删除时间
		/// </summary>
		[Field("DeletionTime")]
		public DateTime? DeletionTime
		{
			get{ return _DeletionTime; }
			set
			{
				this.OnPropertyValueChange("DeletionTime");
				this._DeletionTime = value;
			}
		}
		/// <summary>
		/// 最后一次修改人ID
		/// </summary>
		[Field("LastModifierUserId")]
		public long LastModifierUserId
		{
			get{ return _LastModifierUserId; }
			set
			{
				this.OnPropertyValueChange("LastModifierUserId");
				this._LastModifierUserId = value;
			}
		}
		/// <summary>
		/// 最后的修改时间
		/// </summary>
		[Field("LastModificationTime")]
		public DateTime LastModificationTime
		{
			get{ return _LastModificationTime; }
			set
			{
				this.OnPropertyValueChange("LastModificationTime");
				this._LastModificationTime = value;
			}
		}
		/// <summary>
		/// 状态 0停用 1启用 2作废
		/// </summary>
		[Field("DataStatus")]
		public int DataStatus
		{
			get{ return _DataStatus; }
			set
			{
				this.OnPropertyValueChange("DataStatus");
				this._DataStatus = value;
			}
		}
		/// <summary>
		/// 序号
		/// </summary>
		[Field("No")]
		public int No
		{
			get{ return _No; }
			set
			{
				this.OnPropertyValueChange("No");
				this._No = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.HosId,
				_.Code,
				_.Name,
				_.TitleLevel,
				_.Scope,
				_.SearchCode,
				_.CreatorUserId,
				_.CreationTime,
				_.DeleterUserId,
				_.DeletionTime,
				_.LastModifierUserId,
				_.LastModificationTime,
				_.DataStatus,
				_.No,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._HosId,
				this._Code,
				this._Name,
				this._TitleLevel,
				this._Scope,
				this._SearchCode,
				this._CreatorUserId,
				this._CreationTime,
				this._DeleterUserId,
				this._DeletionTime,
				this._LastModifierUserId,
				this._LastModificationTime,
				this._DataStatus,
				this._No,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Dic_Title");
            /// <summary>
			/// ID
			/// </summary>
			public readonly static Field Id = new Field("Id", "Dic_Title", "ID");
            /// <summary>
			/// 医疗机构ID
			/// </summary>
			public readonly static Field HosId = new Field("HosId", "Dic_Title", "医疗机构ID");
            /// <summary>
			/// 职称编码
			/// </summary>
			public readonly static Field Code = new Field("Code", "Dic_Title", "职称编码");
            /// <summary>
			/// 职称名称
			/// </summary>
			public readonly static Field Name = new Field("Name", "Dic_Title", "职称名称");
            /// <summary>
			/// 职称等级
			/// </summary>
			public readonly static Field TitleLevel = new Field("TitleLevel", "Dic_Title", "职称等级");
            /// <summary>
			/// 范畴 1 医生 2 护士 9其他
			/// </summary>
			public readonly static Field Scope = new Field("Scope", "Dic_Title", "范畴 1 医生 2 护士 9其他");
            /// <summary>
			/// 检索码
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode", "Dic_Title", "检索码");
            /// <summary>
			/// 创建者ID
			/// </summary>
			public readonly static Field CreatorUserId = new Field("CreatorUserId", "Dic_Title", "创建者ID");
            /// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreationTime = new Field("CreationTime", "Dic_Title", "创建时间");
            /// <summary>
			/// 删除者ID
			/// </summary>
			public readonly static Field DeleterUserId = new Field("DeleterUserId", "Dic_Title", "删除者ID");
            /// <summary>
			/// 删除时间
			/// </summary>
			public readonly static Field DeletionTime = new Field("DeletionTime", "Dic_Title", "删除时间");
            /// <summary>
			/// 最后一次修改人ID
			/// </summary>
			public readonly static Field LastModifierUserId = new Field("LastModifierUserId", "Dic_Title", "最后一次修改人ID");
            /// <summary>
			/// 最后的修改时间
			/// </summary>
			public readonly static Field LastModificationTime = new Field("LastModificationTime", "Dic_Title", "最后的修改时间");
            /// <summary>
			/// 状态 0停用 1启用 2作废
			/// </summary>
			public readonly static Field DataStatus = new Field("DataStatus", "Dic_Title", "状态 0停用 1启用 2作废");
            /// <summary>
			/// 序号
			/// </summary>
			public readonly static Field No = new Field("No", "Dic_Title", "序号");
        }
        #endregion
	}
}