//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
    /// <summary>
    /// 实体类Sys_Log。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Sys_Log")]
    [Serializable]
    public partial class Sys_Log : Entity
    {
        #region Model
        private long _HosId;
        private DateTime _CreationTime;
        private string _Action;
        private string _ClassFullName;
        private string _Description;
        private string _ParameterValue;
        private string _ResultValue;
        private long _SessionId;
        private string _Level;

        /// <summary>
        /// 医疗机构ID
        /// </summary>
        [Field("HosId")]
        public long HosId
        {
            get { return _HosId; }
            set
            {
                this.OnPropertyValueChange("HosId");
                this._HosId = value;
            }
        }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Field("CreationTime")]
        public DateTime CreationTime
        {
            get { return _CreationTime; }
            set
            {
                this.OnPropertyValueChange("CreationTime");
                this._CreationTime = value;
            }
        }
        /// <summary>
        /// 动作名称
        /// </summary>
        [Field("Action")]
        public string Action
        {
            get { return _Action; }
            set
            {
                this.OnPropertyValueChange("Action");
                this._Action = value;
            }
        }
        /// <summary>
        /// 操作类的全称
        /// </summary>
        [Field("ClassFullName")]
        public string ClassFullName
        {
            get { return _ClassFullName; }
            set
            {
                this.OnPropertyValueChange("ClassFullName");
                this._ClassFullName = value;
            }
        }
        /// <summary>
        /// 描述
        /// </summary>
        [Field("Description")]
        public string Description
        {
            get { return _Description; }
            set
            {
                this.OnPropertyValueChange("Description");
                this._Description = value;
            }
        }
        /// <summary>
        /// 参数数据
        /// </summary>
        [Field("ParameterValue")]
        public string ParameterValue
        {
            get { return _ParameterValue; }
            set
            {
                this.OnPropertyValueChange("ParameterValue");
                this._ParameterValue = value;
            }
        }
        /// <summary>
        /// 返回值数据
        /// </summary>
        [Field("ResultValue")]
        public string ResultValue
        {
            get { return _ResultValue; }
            set
            {
                this.OnPropertyValueChange("ResultValue");
                this._ResultValue = value;
            }
        }
        /// <summary>
        /// 信使ID
        /// </summary>
        [Field("SessionId")]
        public long SessionId
        {
            get { return _SessionId; }
            set
            {
                this.OnPropertyValueChange("SessionId");
                this._SessionId = value;
            }
        }
        /// <summary>
        /// 日志等级
        /// </summary>
        [Field("Level")]
        public string Level
        {
            get { return _Level; }
            set
            {
                this.OnPropertyValueChange("Level");
                this._Level = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.HosId,
                _.CreationTime,
                _.Action,
                _.ClassFullName,
                _.Description,
                _.ParameterValue,
                _.ResultValue,
                _.SessionId,
                _.Level,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._HosId,
                this._CreationTime,
                this._Action,
                this._ClassFullName,
                this._Description,
                this._ParameterValue,
                this._ResultValue,
                this._SessionId,
                this._Level,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Sys_Log");
            /// <summary>
            /// 医疗机构ID
            /// </summary>
            public readonly static Field HosId = new Field("HosId", "Sys_Log", "医疗机构ID");
            /// <summary>
            /// 创建时间
            /// </summary>
            public readonly static Field CreationTime = new Field("CreationTime", "Sys_Log", "创建时间");
            /// <summary>
            /// 动作名称
            /// </summary>
            public readonly static Field Action = new Field("Action", "Sys_Log", "动作名称");
            /// <summary>
            /// 操作类的全称
            /// </summary>
            public readonly static Field ClassFullName = new Field("ClassFullName", "Sys_Log", "操作类的全称");
            /// <summary>
            /// 描述
            /// </summary>
            public readonly static Field Description = new Field("Description", "Sys_Log", "描述");
            /// <summary>
            /// 参数数据
            /// </summary>
            public readonly static Field ParameterValue = new Field("ParameterValue", "Sys_Log", "参数数据");
            /// <summary>
            /// 返回值数据
            /// </summary>
            public readonly static Field ResultValue = new Field("ResultValue", "Sys_Log", "返回值数据");
            /// <summary>
            /// 信使ID
            /// </summary>
            public readonly static Field SessionId = new Field("SessionId", "Sys_Log", "信使ID");
            /// <summary>
            /// 日志等级
            /// </summary>
            public readonly static Field Level = new Field("Level", "Sys_Log", "日志等级");
        }
        #endregion
    }
}