//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
    /// <summary>
    /// 实体类Sys_UserDeptMapper。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Sys_UserDeptMapper")]
    [Serializable]
    public partial class Sys_UserDeptMapper : Entity
    {
        #region Model
		private long _Id;
		private long _HosId;
		private long _UserId;
		private long _DeptId;
		private long _RoleId;

		/// <summary>
		/// id
		/// </summary>
		[Field("Id")]
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 医疗机构id
		/// </summary>
		[Field("HosId")]
		public long HosId
		{
			get{ return _HosId; }
			set
			{
				this.OnPropertyValueChange("HosId");
				this._HosId = value;
			}
		}
		/// <summary>
		/// 用户id
		/// </summary>
		[Field("UserId")]
		public long UserId
		{
			get{ return _UserId; }
			set
			{
				this.OnPropertyValueChange("UserId");
				this._UserId = value;
			}
		}
		/// <summary>
		/// 用户所拥有科室id
		/// </summary>
		[Field("DeptId")]
		public long DeptId
		{
			get{ return _DeptId; }
			set
			{
				this.OnPropertyValueChange("DeptId");
				this._DeptId = value;
			}
		}
		/// <summary>
		/// 角色Id
		/// </summary>
		[Field("RoleId")]
		public long RoleId
		{
			get{ return _RoleId; }
			set
			{
				this.OnPropertyValueChange("RoleId");
				this._RoleId = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.HosId,
				_.UserId,
				_.DeptId,
				_.RoleId,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._HosId,
				this._UserId,
				this._DeptId,
				this._RoleId,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Sys_UserDeptMapper");
            /// <summary>
			/// id
			/// </summary>
			public readonly static Field Id = new Field("Id", "Sys_UserDeptMapper", "id");
            /// <summary>
			/// 医疗机构id
			/// </summary>
			public readonly static Field HosId = new Field("HosId", "Sys_UserDeptMapper", "医疗机构id");
            /// <summary>
			/// 用户id
			/// </summary>
			public readonly static Field UserId = new Field("UserId", "Sys_UserDeptMapper", "用户id");
            /// <summary>
			/// 用户所拥有科室id
			/// </summary>
			public readonly static Field DeptId = new Field("DeptId", "Sys_UserDeptMapper", "用户所拥有科室id");
            /// <summary>
			/// 角色Id
			/// </summary>
			public readonly static Field RoleId = new Field("RoleId", "Sys_UserDeptMapper", "角色Id");
        }
        #endregion
	}
}