//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace HIS.Model
{

	/// <summary>
	/// 实体类Sys_Dic_Details 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Sys_Dic_Details")]
	[Serializable]
	public partial class Sys_Dic_Details : Entity 
	{
		#region Model
		private long _Id;
		private long _HosId;
		private string _DicCode;
		private string _Code;
		private string _Value;
		private bool _Extensibility;
		private bool _IsBuiltIn;
		private bool _Visible;
		private string _Description;
		private string _SearchCode;
		private string _CreatorUserId;
		private DateTime _CreationTime;
		private string _DeleterUserId;
		private DateTime? _DeletionTime;
		private string _LastModifierUserId;
		private DateTime _LastModificationTime;
		private int _DataStatus;
		private int _No;
		/// <summary>
		/// ID
		/// </summary>
		public long Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 医疗机构ID
		/// </summary>
		public long HosId
		{
			get{ return _HosId; }
			set
			{
				this.OnPropertyValueChange(_.HosId,_HosId,value);
				this._HosId=value;
			}
		}
		/// <summary>
		/// 所属数据字典代码
		/// </summary>
		public string DicCode
		{
			get{ return _DicCode; }
			set
			{
				this.OnPropertyValueChange(_.DicCode,_DicCode,value);
				this._DicCode=value;
			}
		}
		/// <summary>
		/// 代码
		/// </summary>
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange(_.Code,_Code,value);
				this._Code=value;
			}
		}
		/// <summary>
		/// 值
		/// </summary>
		public string Value
		{
			get{ return _Value; }
			set
			{
				this.OnPropertyValueChange(_.Value,_Value,value);
				this._Value=value;
			}
		}
		
		/// <summary>
		/// 是否可扩展  0 否 1 是
		/// </summary>
		public bool Extensibility
		{
			get{ return _Extensibility; }
			set
			{
				this.OnPropertyValueChange(_.Extensibility,_Extensibility,value);
				this._Extensibility=value;
			}
		}
		/// <summary>
		/// 是否系统内置编码  0 否 1 是
		/// </summary>
		public bool IsBuiltIn
		{
			get{ return _IsBuiltIn; }
			set
			{
				this.OnPropertyValueChange(_.IsBuiltIn,_IsBuiltIn,value);
				this._IsBuiltIn=value;
			}
		}
		/// <summary>
		/// 是否允许当做下拉项目时是否可见  1是 0 否
		/// </summary>
		public bool Visible
		{
			get{ return _Visible; }
			set
			{
				this.OnPropertyValueChange(_.Visible,_Visible,value);
				this._Visible=value;
			}
		}
		/// <summary>
		/// 描述
		/// </summary>
		public string Description
		{
			get{ return _Description; }
			set
			{
				this.OnPropertyValueChange(_.Description,_Description,value);
				this._Description=value;
			}
		}
		/// <summary>
		/// 检索码
		/// </summary>
		public string SearchCode
		{
			get{ return _SearchCode; }
			set
			{
				this.OnPropertyValueChange(_.SearchCode,_SearchCode,value);
				this._SearchCode=value;
			}
		}
		/// <summary>
		/// 创建者ID
		/// </summary>
		public string CreatorUserId
		{
			get{ return _CreatorUserId; }
			set
			{
				this.OnPropertyValueChange(_.CreatorUserId,_CreatorUserId,value);
				this._CreatorUserId=value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		public DateTime CreationTime
		{
			get{ return _CreationTime; }
			set
			{
				this.OnPropertyValueChange(_.CreationTime,_CreationTime,value);
				this._CreationTime=value;
			}
		}
		/// <summary>
		/// 删除者ID
		/// </summary>
		public string DeleterUserId
		{
			get{ return _DeleterUserId; }
			set
			{
				this.OnPropertyValueChange(_.DeleterUserId,_DeleterUserId,value);
				this._DeleterUserId=value;
			}
		}
		/// <summary>
		/// 删除时间
		/// </summary>
		public DateTime? DeletionTime
		{
			get{ return _DeletionTime; }
			set
			{
				this.OnPropertyValueChange(_.DeletionTime,_DeletionTime,value);
				this._DeletionTime=value;
			}
		}
		/// <summary>
		/// 最后修改者ID
		/// </summary>
		public string LastModifierUserId
		{
			get{ return _LastModifierUserId; }
			set
			{
				this.OnPropertyValueChange(_.LastModifierUserId,_LastModifierUserId,value);
				this._LastModifierUserId=value;
			}
		}
		/// <summary>
		/// 最后修改时间
		/// </summary>
		public DateTime LastModificationTime
		{
			get{ return _LastModificationTime; }
			set
			{
				this.OnPropertyValueChange(_.LastModificationTime,_LastModificationTime,value);
				this._LastModificationTime=value;
			}
		}
		/// <summary>
		/// 状态 0停用 1启用 2作废
		/// </summary>
		public int DataStatus
		{
			get{ return _DataStatus; }
			set
			{
				this.OnPropertyValueChange(_.DataStatus,_DataStatus,value);
				this._DataStatus=value;
			}
		}
		/// <summary>
		/// 排序
		/// </summary>
		public int No
		{
			get{ return _No; }
			set
			{
				this.OnPropertyValueChange(_.No,_No,value);
				this._No=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.HosId,
				_.DicCode,
				_.Code,
				_.Value,
				_.Extensibility,
				_.IsBuiltIn,
				_.Visible,
				_.Description,
				_.SearchCode,
				_.CreatorUserId,
				_.CreationTime,
				_.DeleterUserId,
				_.DeletionTime,
				_.LastModifierUserId,
				_.LastModificationTime,
				_.DataStatus,
				_.No};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._HosId,
				this._DicCode,
				this._Code,
				this._Value,
				this._Extensibility,
				this._IsBuiltIn,
				this._Visible,
				this._Description,
				this._SearchCode,
				this._CreatorUserId,
				this._CreationTime,
				this._DeleterUserId,
				this._DeletionTime,
				this._LastModifierUserId,
				this._LastModificationTime,
				this._DataStatus,
				this._No};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Sys_Dic_Details");
			/// <summary>
			/// ID
			/// </summary>
			public readonly static Field Id = new Field("Id","Sys_Dic_Details","ID");
			/// <summary>
			/// 医疗机构ID
			/// </summary>
			public readonly static Field HosId = new Field("HosId","Sys_Dic_Details","医疗机构ID");
			/// <summary>
			/// 所属数据字典代码
			/// </summary>
			public readonly static Field DicCode = new Field("DicCode","Sys_Dic_Details","所属数据字典代码");
			/// <summary>
			/// 代码
			/// </summary>
			public readonly static Field Code = new Field("Code","Sys_Dic_Details","代码");
			/// <summary>
			/// 值
			/// </summary>
			public readonly static Field Value = new Field("Value","Sys_Dic_Details","值");
			
			/// <summary>
			/// 是否可扩展  0 否 1 是
			/// </summary>
			public readonly static Field Extensibility = new Field("Extensibility","Sys_Dic_Details","是否可扩展  0 否 1 是");
			/// <summary>
			/// 是否系统内置编码  0 否 1 是
			/// </summary>
			public readonly static Field IsBuiltIn = new Field("IsBuiltIn","Sys_Dic_Details","是否系统内置编码  0 否 1 是");
			/// <summary>
			/// 是否允许当做下拉项目时是否可见  1是 0 否
			/// </summary>
			public readonly static Field Visible = new Field("Visible","Sys_Dic_Details","是否允许当做下拉项目时是否可见  1是 0 否");
			/// <summary>
			/// 描述
			/// </summary>
			public readonly static Field Description = new Field("Description","Sys_Dic_Details","描述");
			/// <summary>
			/// 检索码
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode","Sys_Dic_Details","检索码");
			/// <summary>
			/// 创建者ID
			/// </summary>
			public readonly static Field CreatorUserId = new Field("CreatorUserId","Sys_Dic_Details","创建者ID");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreationTime = new Field("CreationTime","Sys_Dic_Details","创建时间");
			/// <summary>
			/// 删除者ID
			/// </summary>
			public readonly static Field DeleterUserId = new Field("DeleterUserId","Sys_Dic_Details","删除者ID");
			/// <summary>
			/// 删除时间
			/// </summary>
			public readonly static Field DeletionTime = new Field("DeletionTime","Sys_Dic_Details","删除时间");
			/// <summary>
			/// 最后修改者ID
			/// </summary>
			public readonly static Field LastModifierUserId = new Field("LastModifierUserId","Sys_Dic_Details","最后修改者ID");
			/// <summary>
			/// 最后修改时间
			/// </summary>
			public readonly static Field LastModificationTime = new Field("LastModificationTime","Sys_Dic_Details","最后修改时间");
			/// <summary>
			/// 状态 0停用 1启用 2作废
			/// </summary>
			public readonly static Field DataStatus = new Field("DataStatus","Sys_Dic_Details","状态 0停用 1启用 2作废");
			/// <summary>
			/// 排序
			/// </summary>
			public readonly static Field No = new Field("No","Sys_Dic_Details","排序");
		}
		#endregion


	}
}

