//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
	/// <summary>
	/// 实体类Sys_RoleAdditionalInfo。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Sys_RoleAdditionalInfo")]
	[Serializable]
	public partial class Sys_RoleAdditionalInfo : Entity
	{
		#region Model
		private long _Id;
		private long _HosId;
		private long _RoleId;
		private long _UserId;
		private long? _DefaultDeptId;
		private long? _TeacherId;
		private DateTime? _AllowStartTime;
		private DateTime? _AllowEndTime;
		private long _CreatorUserId;
		private DateTime _CreationTime;
		private long? _DeleterUserId;
		private DateTime? _DeletionTime;
		private long _LastModifierUserId;
		private DateTime _LastModificationTime;
		private int _DataStatus;
		private int _No;

		/// <summary>
		/// 
		/// </summary>
		[Field("Id")]
		public long Id
		{
			get { return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("HosId")]
		public long HosId
		{
			get { return _HosId; }
			set
			{
				this.OnPropertyValueChange("HosId");
				this._HosId = value;
			}
		}
		/// <summary>
		/// 角色id
		/// </summary>
		[Field("RoleId")]
		public long RoleId
		{
			get { return _RoleId; }
			set
			{
				this.OnPropertyValueChange("RoleId");
				this._RoleId = value;
			}
		}
		/// <summary>
		/// 用户id
		/// </summary>
		[Field("UserId")]
		public long UserId
		{
			get { return _UserId; }
			set
			{
				this.OnPropertyValueChange("UserId");
				this._UserId = value;
			}
		}
		/// <summary>
		/// 用户在角色下的默认科室
		/// </summary>
		[Field("DefaultDeptId")]
		public long? DefaultDeptId
		{
			get { return _DefaultDeptId; }
			set
			{
				this.OnPropertyValueChange("DefaultDeptId");
				this._DefaultDeptId = value;
			}
		}
		/// <summary>
		/// 带教老师id  当用户性质为试用，进修，实习时必填
		/// </summary>
		[Field("TeacherId")]
		public long? TeacherId
		{
			get { return _TeacherId; }
			set
			{
				this.OnPropertyValueChange("TeacherId");
				this._TeacherId = value;
			}
		}
		/// <summary>
		/// 允许登陆的时间
		/// </summary>
		[Field("AllowStartTime")]
		public DateTime? AllowStartTime
		{
			get { return _AllowStartTime; }
			set
			{
				this.OnPropertyValueChange("AllowStartTime");
				this._AllowStartTime = value;
			}
		}
		/// <summary>
		/// 允许登陆截止的时间
		/// </summary>
		[Field("AllowEndTime")]
		public DateTime? AllowEndTime
		{
			get { return _AllowEndTime; }
			set
			{
				this.OnPropertyValueChange("AllowEndTime");
				this._AllowEndTime = value;
			}
		}
		/// <summary>
		/// 创建者ID
		/// </summary>
		[Field("CreatorUserId")]
		public long CreatorUserId
		{
			get { return _CreatorUserId; }
			set
			{
				this.OnPropertyValueChange("CreatorUserId");
				this._CreatorUserId = value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		[Field("CreationTime")]
		public DateTime CreationTime
		{
			get { return _CreationTime; }
			set
			{
				this.OnPropertyValueChange("CreationTime");
				this._CreationTime = value;
			}
		}
		/// <summary>
		/// 删除者ID
		/// </summary>
		[Field("DeleterUserId")]
		public long? DeleterUserId
		{
			get { return _DeleterUserId; }
			set
			{
				this.OnPropertyValueChange("DeleterUserId");
				this._DeleterUserId = value;
			}
		}
		/// <summary>
		/// 删除时间
		/// </summary>
		[Field("DeletionTime")]
		public DateTime? DeletionTime
		{
			get { return _DeletionTime; }
			set
			{
				this.OnPropertyValueChange("DeletionTime");
				this._DeletionTime = value;
			}
		}
		/// <summary>
		/// 最后一次修改人ID
		/// </summary>
		[Field("LastModifierUserId")]
		public long LastModifierUserId
		{
			get { return _LastModifierUserId; }
			set
			{
				this.OnPropertyValueChange("LastModifierUserId");
				this._LastModifierUserId = value;
			}
		}
		/// <summary>
		/// 最后的修改时间
		/// </summary>
		[Field("LastModificationTime")]
		public DateTime LastModificationTime
		{
			get { return _LastModificationTime; }
			set
			{
				this.OnPropertyValueChange("LastModificationTime");
				this._LastModificationTime = value;
			}
		}
		/// <summary>
		/// 状态 0停用 1启用 2作废
		/// </summary>
		[Field("DataStatus")]
		public int DataStatus
		{
			get { return _DataStatus; }
			set
			{
				this.OnPropertyValueChange("DataStatus");
				this._DataStatus = value;
			}
		}
		/// <summary>
		/// 序号
		/// </summary>
		[Field("No")]
		public int No
		{
			get { return _No; }
			set
			{
				this.OnPropertyValueChange("No");
				this._No = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.HosId,
				_.RoleId,
				_.UserId,
				_.DefaultDeptId,
				_.TeacherId,
				_.AllowStartTime,
				_.AllowEndTime,
				_.CreatorUserId,
				_.CreationTime,
				_.DeleterUserId,
				_.DeletionTime,
				_.LastModifierUserId,
				_.LastModificationTime,
				_.DataStatus,
				_.No,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._HosId,
				this._RoleId,
				this._UserId,
				this._DefaultDeptId,
				this._TeacherId,
				this._AllowStartTime,
				this._AllowEndTime,
				this._CreatorUserId,
				this._CreationTime,
				this._DeleterUserId,
				this._DeletionTime,
				this._LastModifierUserId,
				this._LastModificationTime,
				this._DataStatus,
				this._No,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Sys_RoleAdditionalInfo");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "Sys_RoleAdditionalInfo", "");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field HosId = new Field("HosId", "Sys_RoleAdditionalInfo", "");
			/// <summary>
			/// 角色id
			/// </summary>
			public readonly static Field RoleId = new Field("RoleId", "Sys_RoleAdditionalInfo", "角色id");
			/// <summary>
			/// 用户id
			/// </summary>
			public readonly static Field UserId = new Field("UserId", "Sys_RoleAdditionalInfo", "用户id");
			/// <summary>
			/// 用户在角色下的默认科室
			/// </summary>
			public readonly static Field DefaultDeptId = new Field("DefaultDeptId", "Sys_RoleAdditionalInfo", "用户在角色下的默认科室");
			/// <summary>
			/// 带教老师id  当用户性质为试用，进修，实习时必填
			/// </summary>
			public readonly static Field TeacherId = new Field("TeacherId", "Sys_RoleAdditionalInfo", "带教老师id  当用户性质为试用，进修，实习时必填");
			/// <summary>
			/// 允许登陆的时间
			/// </summary>
			public readonly static Field AllowStartTime = new Field("AllowStartTime", "Sys_RoleAdditionalInfo", "允许登陆的时间");
			/// <summary>
			/// 允许登陆截止的时间
			/// </summary>
			public readonly static Field AllowEndTime = new Field("AllowEndTime", "Sys_RoleAdditionalInfo", "允许登陆截止的时间");
			/// <summary>
			/// 创建者ID
			/// </summary>
			public readonly static Field CreatorUserId = new Field("CreatorUserId", "Sys_RoleAdditionalInfo", "创建者ID");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreationTime = new Field("CreationTime", "Sys_RoleAdditionalInfo", "创建时间");
			/// <summary>
			/// 删除者ID
			/// </summary>
			public readonly static Field DeleterUserId = new Field("DeleterUserId", "Sys_RoleAdditionalInfo", "删除者ID");
			/// <summary>
			/// 删除时间
			/// </summary>
			public readonly static Field DeletionTime = new Field("DeletionTime", "Sys_RoleAdditionalInfo", "删除时间");
			/// <summary>
			/// 最后一次修改人ID
			/// </summary>
			public readonly static Field LastModifierUserId = new Field("LastModifierUserId", "Sys_RoleAdditionalInfo", "最后一次修改人ID");
			/// <summary>
			/// 最后的修改时间
			/// </summary>
			public readonly static Field LastModificationTime = new Field("LastModificationTime", "Sys_RoleAdditionalInfo", "最后的修改时间");
			/// <summary>
			/// 状态 0停用 1启用 2作废
			/// </summary>
			public readonly static Field DataStatus = new Field("DataStatus", "Sys_RoleAdditionalInfo", "状态 0停用 1启用 2作废");
			/// <summary>
			/// 序号
			/// </summary>
			public readonly static Field No = new Field("No", "Sys_RoleAdditionalInfo", "序号");
		}
		#endregion
	}
}