//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace HIS.Model
{
	/// <summary>
	/// 实体类Sys_Parameter。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Sys_Parameter")]
	[Serializable]
	public partial class Sys_Parameter : Entity
	{
		#region Model
		private long _Id;
		private string _ParameterCode;
		private string _ParameterName;
		private string _ParameterValue;
		private string _Description;
		private string _PropertyName;
		private string _SearchCode;
		private long _HosId;
		private long _CreatorUserId;
		private DateTime _CreationTime;
		private long? _DeleterUserId;
		private DateTime? _DeletionTime;
		private long _LastModifierUserId;
		private DateTime _LastModificationTime;
		private int _DataStatus;
		private int _No;

		/// <summary>
		/// ID
		/// </summary>
		[Field("Id")]
		public long Id
		{
			get { return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 参数代码
		/// </summary>
		[Field("ParameterCode")]
		public string ParameterCode
		{
			get { return _ParameterCode; }
			set
			{
				this.OnPropertyValueChange("ParameterCode");
				this._ParameterCode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ParameterName")]
		public string ParameterName
		{
			get { return _ParameterName; }
			set
			{
				this.OnPropertyValueChange("ParameterName");
				this._ParameterName = value;
			}
		}
		/// <summary>
		/// 参数值
		/// </summary>
		[Field("ParameterValue")]
		public string ParameterValue
		{
			get { return _ParameterValue; }
			set
			{
				this.OnPropertyValueChange("ParameterValue");
				this._ParameterValue = value;
			}
		}
		/// <summary>
		/// 描述
		/// </summary>
		[Field("Description")]
		public string Description
		{
			get { return _Description; }
			set
			{
				this.OnPropertyValueChange("Description");
				this._Description = value;
			}
		}
		/// <summary>
		/// 代码中得属性名
		/// </summary>
		[Field("PropertyName")]
		public string PropertyName
		{
			get { return _PropertyName; }
			set
			{
				this.OnPropertyValueChange("PropertyName");
				this._PropertyName = value;
			}
		}
		/// <summary>
		/// 检索码
		/// </summary>
		[Field("SearchCode")]
		public string SearchCode
		{
			get { return _SearchCode; }
			set
			{
				this.OnPropertyValueChange("SearchCode");
				this._SearchCode = value;
			}
		}
		/// <summary>
		/// 医疗机构ID
		/// </summary>
		[Field("HosId")]
		public long HosId
		{
			get { return _HosId; }
			set
			{
				this.OnPropertyValueChange("HosId");
				this._HosId = value;
			}
		}
		/// <summary>
		/// 创建者ID
		/// </summary>
		[Field("CreatorUserId")]
		public long CreatorUserId
		{
			get { return _CreatorUserId; }
			set
			{
				this.OnPropertyValueChange("CreatorUserId");
				this._CreatorUserId = value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		[Field("CreationTime")]
		public DateTime CreationTime
		{
			get { return _CreationTime; }
			set
			{
				this.OnPropertyValueChange("CreationTime");
				this._CreationTime = value;
			}
		}
		/// <summary>
		/// 删除者ID
		/// </summary>
		[Field("DeleterUserId")]
		public long? DeleterUserId
		{
			get { return _DeleterUserId; }
			set
			{
				this.OnPropertyValueChange("DeleterUserId");
				this._DeleterUserId = value;
			}
		}
		/// <summary>
		/// 删除者信息
		/// </summary>
		[Field("DeletionTime")]
		public DateTime? DeletionTime
		{
			get { return _DeletionTime; }
			set
			{
				this.OnPropertyValueChange("DeletionTime");
				this._DeletionTime = value;
			}
		}
		/// <summary>
		/// 修改者ID
		/// </summary>
		[Field("LastModifierUserId")]
		public long LastModifierUserId
		{
			get { return _LastModifierUserId; }
			set
			{
				this.OnPropertyValueChange("LastModifierUserId");
				this._LastModifierUserId = value;
			}
		}
		/// <summary>
		/// 修改时间
		/// </summary>
		[Field("LastModificationTime")]
		public DateTime LastModificationTime
		{
			get { return _LastModificationTime; }
			set
			{
				this.OnPropertyValueChange("LastModificationTime");
				this._LastModificationTime = value;
			}
		}
		/// <summary>
		/// _0停用 1启用 2作废
		/// </summary>
		[Field("DataStatus")]
		public int DataStatus
		{
			get { return _DataStatus; }
			set
			{
				this.OnPropertyValueChange("DataStatus");
				this._DataStatus = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("No")]
		public int No
		{
			get { return _No; }
			set
			{
				this.OnPropertyValueChange("No");
				this._No = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.ParameterCode,
				_.ParameterName,
				_.ParameterValue,
				_.Description,
				_.PropertyName,
				_.SearchCode,
				_.HosId,
				_.CreatorUserId,
				_.CreationTime,
				_.DeleterUserId,
				_.DeletionTime,
				_.LastModifierUserId,
				_.LastModificationTime,
				_.DataStatus,
				_.No,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._ParameterCode,
				this._ParameterName,
				this._ParameterValue,
				this._Description,
				this._PropertyName,
				this._SearchCode,
				this._HosId,
				this._CreatorUserId,
				this._CreationTime,
				this._DeleterUserId,
				this._DeletionTime,
				this._LastModifierUserId,
				this._LastModificationTime,
				this._DataStatus,
				this._No,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Sys_Parameter");
			/// <summary>
			/// ID
			/// </summary>
			public readonly static Field Id = new Field("Id", "Sys_Parameter", "ID");
			/// <summary>
			/// 参数代码
			/// </summary>
			public readonly static Field ParameterCode = new Field("ParameterCode", "Sys_Parameter", "参数代码");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParameterName = new Field("ParameterName", "Sys_Parameter", "");
			/// <summary>
			/// 参数值
			/// </summary>
			public readonly static Field ParameterValue = new Field("ParameterValue", "Sys_Parameter", "参数值");
			/// <summary>
			/// 描述
			/// </summary>
			public readonly static Field Description = new Field("Description", "Sys_Parameter", "描述");
			/// <summary>
			/// 代码中得属性名
			/// </summary>
			public readonly static Field PropertyName = new Field("PropertyName", "Sys_Parameter", "代码中得属性名");
			/// <summary>
			/// 检索码
			/// </summary>
			public readonly static Field SearchCode = new Field("SearchCode", "Sys_Parameter", "检索码");
			/// <summary>
			/// 医疗机构ID
			/// </summary>
			public readonly static Field HosId = new Field("HosId", "Sys_Parameter", "医疗机构ID");
			/// <summary>
			/// 创建者ID
			/// </summary>
			public readonly static Field CreatorUserId = new Field("CreatorUserId", "Sys_Parameter", "创建者ID");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreationTime = new Field("CreationTime", "Sys_Parameter", "创建时间");
			/// <summary>
			/// 删除者ID
			/// </summary>
			public readonly static Field DeleterUserId = new Field("DeleterUserId", "Sys_Parameter", "删除者ID");
			/// <summary>
			/// 删除者信息
			/// </summary>
			public readonly static Field DeletionTime = new Field("DeletionTime", "Sys_Parameter", "删除者信息");
			/// <summary>
			/// 修改者ID
			/// </summary>
			public readonly static Field LastModifierUserId = new Field("LastModifierUserId", "Sys_Parameter", "修改者ID");
			/// <summary>
			/// 修改时间
			/// </summary>
			public readonly static Field LastModificationTime = new Field("LastModificationTime", "Sys_Parameter", "修改时间");
			/// <summary>
			/// _0停用 1启用 2作废
			/// </summary>
			public readonly static Field DataStatus = new Field("DataStatus", "Sys_Parameter", "_0停用 1启用 2作废");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field No = new Field("No", "Sys_Parameter", "");
		}
		#endregion
	}
}